# Generated by Django 5.1.15 on 2026-05-04 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0005_add_booking_token'),
        ('customers', '0002_add_referral_code'),
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author_was_clinical', models.BooleanField(default=False, help_text='Whether the author held a clinical job title at signing. Snapshot — does NOT update if the provider changes job title later. Used as the legal-status anchor on the record.')),
                ('signed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Set on creation; never updated.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chart_notes', to='appointments.appointment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chart_notes_authored', to='tenants.tenantmembership')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chart_notes', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-signed_at'],
                'indexes': [models.Index(fields=['tenant', 'customer', '-signed_at'], name='charts_char_tenant__6f4aeb_idx'), models.Index(fields=['tenant', 'author', '-signed_at'], name='charts_char_tenant__33ae53_idx')],
            },
        ),
    ]
