# Generated by Django 5.1.15 on 2026-05-05 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_add_booking_token'),
        ('charts', '0001_initial'),
        ('customers', '0002_add_referral_code'),
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartnote',
            name='is_voided',
            field=models.BooleanField(db_index=True, default=False, help_text='True when an owner/manager has invalidated this note. Voided notes are excluded from clinical reads by default and rendered struck-through; the row survives.'),
        ),
        migrations.AddField(
            model_name='chartnote',
            name='parent_note',
            field=models.ForeignKey(blank=True, help_text='When set, this row is an addendum to another (locked) note. Top-level notes have parent_note=NULL. Only one level of nesting allowed — addenda cannot have addenda.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='charts.chartnote'),
        ),
        migrations.AddField(
            model_name='chartnote',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartnote',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_chart_notes', to='tenants.tenantmembership'),
        ),
        migrations.AddField(
            model_name='chartnote',
            name='voided_reason',
            field=models.CharField(blank=True, default='', help_text='Operator-authored justification for the void ("wrong patient", "signed in error", etc.). Required when voiding.', max_length=500),
        ),
        migrations.AddIndex(
            model_name='chartnote',
            index=models.Index(fields=['tenant', 'parent_note', 'signed_at'], name='charts_char_tenant__402786_idx'),
        ),
    ]
