# Generated by Django 5.1.15 on 2026-05-16 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_review_request_sms_provider_id_and_more'),
        ('charts', '0002_chartnote_is_voided_chartnote_parent_note_and_more'),
        ('customers', '0003_customer_email_marketing_consent_at_and_more'),
        ('services', '0004_serviceprotocol'),
        ('tenants', '0012_tenant_confirmation_sms_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentRecordTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Operator-facing label, e.g. "Botox treatment record" or "HydraFacial treatment record".', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Internal notes about when to use this template.')),
                ('schema', models.JSONField(default=dict, help_text='Field definitions — same shape as FormTemplate.schema: {"fields": [{"id": "...", "type": "...", "label": "...", "required": true, ...}]}. Validated by the serializer.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Auto-incremented when `schema` changes. TreatmentRecord submissions snapshot the version they were signed against so historical records stay legible after the template evolves.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates stop appearing in the "create record" picker for new appointments. Existing records are unaffected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version_at_signing', models.PositiveIntegerField(help_text='Snapshot of `template.version` at signing time. The reader uses this + `schema_snapshot` to render the record as it was at the moment of signing, regardless of subsequent template changes.')),
                ('schema_snapshot', models.JSONField(default=dict, help_text="Frozen copy of the template's schema at signing time. Lets the read-back render labels + field types even after the template has been edited or deactivated.")),
                ('answers', models.JSONField(default=dict, help_text="PHI. Provider's responses keyed by field id. Shape validated against `schema_snapshot` by the serializer.")),
                ('author_was_clinical', models.BooleanField(default=False, help_text='Whether the author held a clinical job title at signing. Snapshot — does NOT update if the provider changes job title later. Used as the legal-status anchor on the record.')),
                ('signed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Set on creation; never updated.')),
                ('is_voided', models.BooleanField(db_index=True, default=False, help_text='True when an owner/manager has invalidated this record. Voided records are excluded from clinical reads by default and rendered struck-through; the row survives.')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('voided_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text='The appointment this record documents. SET_NULL on appointment delete because clinical records outlive the operational reason they were written.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_records', to='appointments.appointment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_records_authored', to='tenants.tenantmembership')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treatment_records', to='customers.customer')),
                ('parent_record', models.ForeignKey(blank=True, help_text='When set, this row is an addendum to another (locked) record. Top-level records have parent_record=NULL. Only one level of nesting allowed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='addenda', to='charts.treatmentrecord')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_treatment_records', to='tenants.tenantmembership')),
                ('template', models.ForeignKey(help_text='PROTECT — templates with submitted records cannot be deleted; deactivate (is_active=False) to retire.', on_delete=django.db.models.deletion.PROTECT, related_name='records', to='charts.treatmentrecordtemplate')),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTreatmentTemplateAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_template_assignments', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='charts.treatmentrecordtemplate')),
            ],
        ),
        migrations.AddIndex(
            model_name='treatmentrecordtemplate',
            index=models.Index(fields=['tenant', 'is_active', 'name'], name='charts_trea_tenant__bfc578_idx'),
        ),
        migrations.AddConstraint(
            model_name='treatmentrecordtemplate',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='trt_template_unique_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='treatmentrecord',
            index=models.Index(fields=['tenant', 'customer', '-signed_at'], name='charts_trea_tenant__f2237d_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentrecord',
            index=models.Index(fields=['tenant', 'author', '-signed_at'], name='charts_trea_tenant__0d6265_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentrecord',
            index=models.Index(fields=['tenant', 'appointment', '-signed_at'], name='charts_trea_tenant__1af1a6_idx'),
        ),
        migrations.AddIndex(
            model_name='treatmentrecord',
            index=models.Index(fields=['tenant', 'parent_record', 'signed_at'], name='charts_trea_tenant__14b4f6_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicetreatmenttemplateassignment',
            constraint=models.UniqueConstraint(fields=('template', 'service'), name='trt_template_assignment_unique'),
        ),
    ]
