# Generated by Django 5.1.15 on 2026-05-06 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0005_add_booking_token'),
        ('customers', '0003_customer_email_marketing_consent_at_and_more'),
        ('invoices', '0005_remove_invoicelineitem_invoice_lines_service_xor_product_and_more'),
        ('services', '0003_add_code_tax_type'),
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Short identifier. Auto-generated from the name on first save; editable. Unique within the tenant.', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Per-cycle price. Snapshotted onto the source invoice line.')),
                ('tax_rate_percent', models.DecimalField(decimal_places=3, default=0, help_text='Tax rate as a percent. Whether to tax memberships varies by jurisdiction; default 0.', max_digits=6)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', help_text='How often the membership is billed. Each Subscription represents one cycle.', max_length=20)),
                ('member_discount_percent', models.DecimalField(decimal_places=2, default=0, help_text='Implicit member rate on a-la-carte services. Snapshotted onto the Subscription. Not auto-applied at invoice time in v1 — operator overrides unit_price_cents manually.', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive plans stay on past subscriptions but cannot be sold on new invoices.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_per_cycle', models.PositiveIntegerField(default=1, help_text='Credits granted at the start of each billing cycle. v1 is use-it-or-lose-it — unredeemed credits do NOT carry over.')),
                ('sort_order', models.IntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='memberships.membershipplan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('billing_interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('member_discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('started_at', models.DateTimeField(blank=True, help_text='Set when the source invoice closes (PENDING→ACTIVE).', null=True)),
                ('current_period_starts_at', models.DateTimeField(blank=True, null=True)),
                ('current_period_ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('auto_renew', models.BooleanField(default=False, help_text='When true (and a payment processor is wired in Phase 2A), a cron generates next-cycle invoices automatically. v1 ignores this; renewal is operator-driven.')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='customers.customer')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='memberships.membershipplan')),
                ('source_invoice_line', models.OneToOneField(help_text='The invoice line that paid for this cycle.', on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='invoices.invoicelineitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('quantity_per_cycle', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('unit_value_cents', models.PositiveIntegerField(default=0, help_text="Snapshot of the service's a-la-carte price at sale time. Used as the redemption line value (analogous to PurchasedPackageItem.unit_value_cents).")),
                ('sort_order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='memberships.subscription')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Signed: positive for a normal redeem, negative for a reversal.')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_redemptions', to='appointments.appointment')),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='invoices.invoicelineitem')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='memberships.subscriptionitem')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='memberships.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='membershipplan',
            index=models.Index(fields=['tenant', 'is_active', 'name'], name='memberships_tenant__851aef_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipplan',
            index=models.Index(fields=['tenant', 'sku'], name='memberships_tenant__5c0835_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipplan',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('tenant', 'sku'), name='membership_plans_unique_tenant_sku'),
        ),
        migrations.AddConstraint(
            model_name='membershipplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'service'), name='membership_plan_items_unique_plan_service'),
        ),
        migrations.AddConstraint(
            model_name='membershipplanitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_per_cycle__gt', 0)), name='membership_plan_items_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='memberships_tenant__fa3290_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant', 'status', 'current_period_ends_at'], name='memberships_tenant__002a12_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(fields=('subscription', 'service'), name='subscription_items_unique'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__lte', models.F('quantity_per_cycle'))), name='subscription_items_remaining_lte_per_cycle'),
        ),
        migrations.AddIndex(
            model_name='subscriptionredemption',
            index=models.Index(fields=['tenant', 'subscription', '-redeemed_at'], name='memberships_tenant__d9015b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionredemption',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='subscription_redemptions_quantity_nonzero'),
        ),
    ]
