# Generated by Django 5.1.15 on 2026-05-21 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_subscription_import_provenance'),
        ('services', '0006_service_hero_photo'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membershipplanitem',
            name='membership_plan_items_unique_plan_service',
        ),
        migrations.RemoveConstraint(
            model_name='subscriptionitem',
            name='subscription_items_unique',
        ),
        migrations.AddField(
            model_name='membershipplanitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='A whole service category — any service in it is redeemable. Null when this line is a single service.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Set when this credit covers a whole category — any service in it is redeemable. Null for a single-service credit.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.servicecategory'),
        ),
        migrations.AddField(
            model_name='subscriptionitem',
            name='category_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='membershipplanitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='A specific included service. Null when this line is a category.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text="FK to the catalog Service. NULL for a category credit, or for a migration-imported row whose upstream service name didn't match any Lumè Service — the snapshot `service_name` still displays so the operator can manually map / redeem.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service'),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='service_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subscriptionitem',
            name='unit_value_cents',
            field=models.PositiveIntegerField(default=0, help_text="Snapshot of the service's a-la-carte price at sale time (single-service credits only). 0 for a category credit — its value depends on which service is redeemed."),
        ),
        migrations.AddConstraint(
            model_name='membershipplanitem',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('plan', 'service'), name='membership_plan_items_unique_plan_service'),
        ),
        migrations.AddConstraint(
            model_name='membershipplanitem',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('plan', 'category'), name='membership_plan_items_unique_plan_category'),
        ),
        migrations.AddConstraint(
            model_name='membershipplanitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('service__isnull', False)), models.Q(('category__isnull', False), ('service__isnull', True)), _connector='OR'), name='membership_plan_items_service_xor_category'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('service__isnull', False)), fields=('subscription', 'service'), name='subscription_items_unique'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionitem',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False)), fields=('subscription', 'category'), name='subscription_items_unique_category'),
        ),
    ]
