# Generated by Django 5.1.15 on 2026-04-30 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_add_referral_code'),
        ('services', '0003_add_code_tax_type'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked in'), ('completed', 'Completed'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], db_index=True, default='booked', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes visible to staff.')),
                ('source', models.CharField(blank=True, help_text="e.g. 'staff', 'online', 'zenoti_import'", max_length=50)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_reason', models.CharField(blank=True, max_length=200)),
                ('quoted_price_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='customers.customer')),
                ('provider', models.ForeignKey(help_text='Staff member performing the service. Must have is_bookable=True.', on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='tenants.tenantmembership')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['tenant', 'start_time'], name='appointment_tenant__b7491c_idx'), models.Index(fields=['tenant', 'provider', 'start_time'], name='appointment_tenant__d6ec26_idx'), models.Index(fields=['tenant', 'customer', '-start_time'], name='appointment_tenant__dfa9bf_idx'), models.Index(fields=['tenant', 'status', 'start_time'], name='appointment_tenant__4d1145_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='appointments_end_after_start')],
            },
        ),
    ]
