# Generated by Django 5.1.15 on 2026-05-02 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('customers', '0002_add_referral_code'),
        ('services', '0003_add_code_tax_type'),
        ('tenants', '0006_seed_default_location_per_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='tenants.location'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(help_text="Staff member performing the service. Must have is_bookable=True AND be assigned (via MembershipLocation) to the appointment's location.", on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='tenants.tenantmembership'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['tenant', 'location', 'start_time'], name='appointment_tenant__397af0_idx'),
        ),
    ]
