"""Finalise: `Appointment.location` becomes non-null.

Phase 3 of the appointment-location rollout (see 0002 + 0003 for
context). At this point every existing row has been backfilled to its
tenant's default location, so flipping the column to NOT NULL is
trivial. New rows always require a location — the API defaults it from
`request.location` when the caller doesn't provide one.

Hand-written rather than autogenerated because Django's autodetector
asks for a default value (interactive prompt), which doesn't apply
here — the backfill in 0003 already populated everything.
"""

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_backfill_appointment_location'),
        ('tenants', '0006_seed_default_location_per_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='location',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='appointments',
                to='tenants.location',
            ),
        ),
    ]
