# Generated by Django 5.1.15 on 2026-05-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_location_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booking_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
