# Generated by Django 5.1.15 on 2026-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_add_booking_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='confirmation_sms_provider_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='confirmation_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sms_provider_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
