# Generated by Django 5.1.15 on 2026-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_appointment_confirmation_sms_provider_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='review_request_sms_provider_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='appointment',
            name='review_request_sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
