# Generated by Django 5.1.15 on 2026-05-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_review_request_sms_provider_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='external_source',
            field=models.CharField(blank=True, help_text="e.g. 'zenoti', 'vagaro'", max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
