# Generated by Django 5.1.15 on 2026-05-21 18:11

import django.db.models.deletion
from django.db import migrations, models


def backfill_primary_invoice_line(apps, schema_editor):
    """Link each existing appointment to the invoice line that bills its
    service. The invoice-creation signal makes exactly one line per
    appointment at creation time, so for almost every row there is a
    single line whose `service_id` matches the appointment's service.
    When that match is ambiguous (zero or several), leave the link null
    — the "change service" action falls back to skipping invoice sync.
    """
    Appointment = apps.get_model('appointments', 'Appointment')
    Invoice = apps.get_model('invoices', 'Invoice')
    InvoiceLineItem = apps.get_model('invoices', 'InvoiceLineItem')

    for appt in Appointment.objects.all().iterator():
        invoice = Invoice.objects.filter(appointment_id=appt.pk).first()
        if invoice is None:
            continue
        line_ids = list(
            InvoiceLineItem.objects
            .filter(invoice_id=invoice.pk, service_id=appt.service_id)
            .values_list('pk', flat=True)
        )
        if len(line_ids) == 1:
            appt.primary_invoice_line_id = line_ids[0]
            appt.save(update_fields=['primary_invoice_line'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_appointment_import_provenance'),
        ('invoices', '0007_invoice_gift_card_credits_cents_and_more'),
        ('services', '0006_service_hero_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='primary_invoice_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoices.invoicelineitem'),
        ),
        migrations.CreateModel(
            name='AppointmentService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Snapshot of the service price when it was added.')),
                ('duration_minutes', models.PositiveIntegerField(default=0, help_text='Snapshot of the service duration when it was added.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_services', to='appointments.appointment')),
                ('invoice_line', models.OneToOneField(blank=True, help_text='The invoice line this service generated. Null once the line is removed, or when the invoice could not be synced.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='invoices.invoicelineitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['appointment', 'sort_order'], name='appointment_appoint_a4fb30_idx')],
            },
        ),
        migrations.RunPython(backfill_primary_invoice_line, noop_reverse),
    ]
