# Generated by Django 5.1.15 on 2026-05-26 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_appointment_primary_invoice_line_appointmentservice'),
        ('tenants', '0012_tenant_confirmation_sms_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(help_text='Why the time is blocked. Frontend offers presets (Lunch, Personal time, Training, Meeting, Admin, Out of office) plus a free-form Other.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_blocks_created', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_blocks', to='tenants.location')),
                ('provider', models.ForeignKey(help_text='The staff member whose calendar is being blocked.', on_delete=django.db.models.deletion.PROTECT, related_name='time_blocks', to='tenants.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['tenant', 'location', 'start_time'], name='appointment_tenant__582b21_idx'), models.Index(fields=['tenant', 'provider', 'start_time'], name='appointment_tenant__7f167a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='time_blocks_end_after_start')],
            },
        ),
    ]
