# Generated by Django 5.1.15 on 2026-05-27 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_timeblock'),
        ('tenants', '0012_tenant_confirmation_sms_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentservice',
            name='provider',
            field=models.ForeignKey(blank=True, help_text="Staff member performing this service. Null inherits the appointment's primary provider.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenantmembership'),
        ),
    ]
