# Generated by Django 5.1.15 on 2026-05-06 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_email_marketing_consent_at_and_more'),
        ('invoices', '0006_remove_invoicelineitem_invoice_lines_at_most_one_source_and_more'),
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Customer-presented redemption code, format 'GC-XXXX-YYYY'. Auto-generated on first save; unique within tenant.", max_length=20)),
                ('issued_to_name', models.CharField(blank=True, default='', help_text='Recipient name. When `issued_to_customer` is set, this can be left blank and the customer name is used. Required when issuing without a customer FK.', max_length=200)),
                ('issued_to_email', models.EmailField(blank=True, default='', help_text='Recipient email for the digital-card link (post-MVP).', max_length=254)),
                ('initial_value_cents', models.PositiveIntegerField(help_text='Original face value at sale time. Never mutates.')),
                ('balance_cents', models.PositiveIntegerField(help_text='Current redeemable balance. Mutates on every redeem / reversal / adjustment. Sum of ledger entries should equal this value (verified in tests).')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('voided', 'Voided'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, help_text='Set when the source invoice closes (PENDING→ACTIVE).', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration. Null = never. Past-expiry cards are rejected at redeem-time; a nightly cron to flip status to EXPIRED is out of scope for v1.', null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='', help_text='Private operator notes — never shown to recipient.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_to_customer', models.ForeignKey(blank=True, help_text="The customer this card was issued to. Null when sold as a gift to a non-customer (recipient won't be in the system until they walk in for a redemption).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards_received', to='customers.customer')),
                ('purchaser_customer', models.ForeignKey(blank=True, help_text='The customer who paid (often != recipient when sold as a gift).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_cards_purchased', to='customers.customer')),
                ('source_invoice_line', models.OneToOneField(help_text='The invoice line that paid for this card.', on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_issued', to='invoices.invoicelineitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCardLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('issue', 'Issue'), ('redeem', 'Redeem'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], db_index=True, max_length=20)),
                ('amount_cents', models.IntegerField(help_text='Signed: positive for issue / reversal / positive adjustment, negative for redeem / negative adjustment.')),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gift_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='giftcards.giftcard')),
                ('invoice', models.ForeignKey(blank=True, help_text='The invoice this entry was applied against. Null for manual adjustments + the initial ISSUE row (which references the source invoice via gift_card.source_invoice_line).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gift_card_ledger_entries', to='invoices.invoice')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['tenant', 'status'], name='giftcards_g_tenant__a78f87_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['tenant', 'issued_to_customer'], name='giftcards_g_tenant__e64ee1_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['tenant', 'purchaser_customer'], name='giftcards_g_tenant__7727f0_idx'),
        ),
        migrations.AddConstraint(
            model_name='giftcard',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='gift_cards_unique_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='giftcardledger',
            index=models.Index(fields=['tenant', 'gift_card', '-recorded_at'], name='giftcards_g_tenant__ccc6e7_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcardledger',
            index=models.Index(fields=['tenant', 'invoice'], name='giftcards_g_tenant__969eda_idx'),
        ),
        migrations.AddConstraint(
            model_name='giftcardledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'issue'), ('amount_cents__gt', 0)), models.Q(('kind', 'redeem'), ('amount_cents__lt', 0)), models.Q(('kind', 'reversal'), ('amount_cents__gt', 0)), ('kind', 'adjustment'), _connector='OR'), name='gift_card_ledger_amount_sign_matches_kind'),
        ),
        migrations.AddConstraint(
            model_name='giftcardledger',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents', 0), _negated=True), name='gift_card_ledger_amount_nonzero'),
        ),
    ]
