# Generated by Django 5.1.15 on 2026-05-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0007_invoice_gift_card_credits_cents_and_more'),
        ('services', '0003_add_code_tax_type'),
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_rate_percent', models.DecimalField(decimal_places=2, default=0, help_text='Default commission percent on services performed by this staff member. Overridden per service category via `CommissionRuleOverride`.', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='When false, no new commission accrues for this staff member. Existing entries stay.')),
                ('notes', models.TextField(blank=True, default='', help_text='Private operator notes (e.g. "raise effective Mar 1").')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rule', to='tenants.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['membership__user__last_name', 'membership__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRuleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_percent', models.DecimalField(decimal_places=2, help_text='Override percent for services in this category.', max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='services.servicecategory')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='commissions.commissionrule')),
            ],
            options={
                'ordering': ['category__name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('accrual', 'Accrual'), ('reversal', 'Reversal')], db_index=True, max_length=20)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('line_subtotal_cents', models.PositiveIntegerField()),
                ('amount_cents', models.IntegerField(help_text='Signed cents: positive on accrual, negative on reversal.')),
                ('accrued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_entries', to='invoices.invoice')),
                ('invoice_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_entries', to='invoices.invoicelineitem')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_entries', to='tenants.tenantmembership')),
                ('reverses', models.OneToOneField(blank=True, help_text='When kind=REVERSAL, points back at the ACCRUAL row.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='commissions.commissionentry')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-accrued_at'],
                'indexes': [models.Index(fields=['tenant', 'membership', '-accrued_at'], name='commission_per_staff_idx'), models.Index(fields=['tenant', 'invoice'], name='commission_per_invoice_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount_cents', 0), _negated=True), name='commission_entries_amount_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'accrual'), ('amount_cents__gt', 0)), models.Q(('kind', 'reversal'), ('amount_cents__lt', 0)), _connector='OR'), name='commission_entries_amount_sign_matches_kind')],
            },
        ),
        migrations.AddConstraint(
            model_name='commissionrule',
            constraint=models.CheckConstraint(condition=models.Q(('base_rate_percent__gte', 0), ('base_rate_percent__lte', 100)), name='commission_rule_base_rate_0_to_100'),
        ),
        migrations.AddConstraint(
            model_name='commissionruleoverride',
            constraint=models.UniqueConstraint(fields=('rule', 'category'), name='commission_overrides_unique_rule_category'),
        ),
        migrations.AddConstraint(
            model_name='commissionruleoverride',
            constraint=models.CheckConstraint(condition=models.Q(('rate_percent__gte', 0), ('rate_percent__lte', 100)), name='commission_override_rate_0_to_100'),
        ),
    ]
