# Generated by Django 5.1.15 on 2026-04-30 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', help_text='Hex color used on the calendar block and the service chip.', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Time blocked on the calendar for this service.')),
                ('buffer_minutes', models.PositiveIntegerField(default=0, help_text='Cleanup / setup time after each appointment, kept off the bookable schedule.')),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Price in cents (integer). Divide by 100 for the dollar amount.')),
                ('is_bookable_online', models.BooleanField(default=True, help_text='If false, the service is staff-only — does not appear on the public booking page.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive services stay in history (existing appointments / invoices) but cannot be booked.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.servicecategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'name'], name='services_se_tenant__b5740a_idx'), models.Index(fields=['tenant', 'category'], name='services_se_tenant__a64e6e_idx'), models.Index(fields=['tenant', 'is_bookable_online'], name='services_se_tenant__04dcdc_idx')],
            },
        ),
    ]
