# Generated by Django 5.1.15 on 2026-04-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='eligible_job_titles',
            field=models.ManyToManyField(blank=True, help_text='Which job titles can perform services in this category. Empty = no restriction. Enforced when assigning a provider to an appointment in this category (Phase 1D).', related_name='eligible_categories', to='tenants.jobtitle'),
        ),
    ]
