# Generated by Django 5.1.15 on 2026-04-30 — add `code`, `service_type`,
# `tax_rate_percent` to Service. The `code` rollout follows the same three-step
# pattern as the customer referral_code migration: add column blank, backfill,
# then apply the partial unique constraint.

import re

from django.db import migrations, models


def generate_code(name: str) -> str:
    """Inline copy of `apps.services.models.generate_service_code` so the
    migration is self-contained and not coupled to runtime model code."""
    words = re.findall(r'[A-Za-z]+', name)[:3]
    initials = ''.join(w[0].upper() for w in words) if words else 'SVC'
    nums = re.findall(r'\d+', name)
    suffix = nums[0] if nums else ''
    return f'{initials}{suffix}' or 'SVC'


def backfill_codes(apps, schema_editor):
    Service = apps.get_model('services', 'Service')

    seen_per_tenant: dict[int, set[str]] = {}
    for code, tenant_id in Service.objects.exclude(code='').values_list('code', 'tenant_id'):
        seen_per_tenant.setdefault(tenant_id, set()).add(code)

    for service in Service.objects.filter(code=''):
        seen = seen_per_tenant.setdefault(service.tenant_id, set())
        base = generate_code(service.name)
        candidate = base
        attempt = 1
        while candidate in seen:
            attempt += 1
            candidate = f'{base}-{attempt}'
            if attempt > 50:
                raise RuntimeError(
                    f'Could not generate a unique code for service {service.pk}',
                )
        service.code = candidate
        service.save(update_fields=['code'])
        seen.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicecategory_eligible_job_titles'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text=(
                    'Short SKU-style identifier. Auto-generated from the name on first save; '
                    'editable. Unique within the tenant.'
                ),
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(
                choices=[('regular', 'Regular service'), ('addon', 'Add-on')],
                default='regular',
                help_text='Regular services book on the calendar. Add-ons attach to a regular appointment.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='service',
            name='tax_rate_percent',
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text='Tax rate as a percent (e.g. 8.875 for NYC combined). Applied at invoice time.',
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(
                default=60,
                help_text='Time blocked on the calendar when this service is booked.',
            ),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'service_type'], name='services_se_tenant__214828_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['tenant', 'code'], name='services_se_tenant__c52003_idx'),
        ),
        migrations.RunPython(backfill_codes, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(
                condition=models.Q(('code', ''), _negated=True),
                fields=('tenant', 'code'),
                name='services_unique_tenant_code',
            ),
        ),
    ]
