# Generated by Django 5.1.15 on 2026-05-15 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_add_code_tax_type'),
        ('tenants', '0012_tenant_confirmation_sms_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_treatment', models.TextField(blank=True, default='', help_text='Pre-treatment checks: contraindications, allergies, skin assessment, consent confirmation, photos.')),
                ('intra_treatment', models.TextField(blank=True, default='', help_text='The procedure itself. Numbered steps, equipment settings, technique notes.')),
                ('post_treatment', models.TextField(blank=True, default='', help_text='Immediate post-care + take-home guidance for the customer. Sun avoidance, retinoid pause, side-effect expectations.')),
                ('notes', models.TextField(blank=True, default='', help_text='Free-form internal notes — lot tracking conventions, vendor preferences, exclusion criteria.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(help_text='The catalog service this protocol applies to. CASCADE — if the service is deleted, the protocol goes with it. Soft-delete (is_active=False) keeps both intact.', on_delete=django.db.models.deletion.CASCADE, related_name='protocol', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('updated_by', models.ForeignKey(blank=True, help_text='The User who last saved this protocol.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['service__name'],
            },
        ),
    ]
