# Generated by Django 5.1.15 on 2026-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_serviceprotocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='external_source',
            field=models.CharField(blank=True, help_text="e.g. 'zenoti', 'vagaro'", max_length=50),
        ),
        migrations.AddField(
            model_name='service',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Short SKU-style identifier. Auto-generated from the name on first save; editable. Unique within the tenant. Widened to 50 chars to fit longer imported codes (Zenoti emits e.g. `addon-acneandoilcontrotx`).', max_length=50),
        ),
    ]
