# Generated by Django 5.1.15 on 2026-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_service_provenance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hero_photo',
            field=models.ImageField(blank=True, help_text='Optional hero image shown on the public booking page.', null=True, upload_to='services/hero/%Y/%m/'),
        ),
    ]
