"""DRF serializers for the form-templates API.

The schema validation is the substantive piece — the JSON shape that
clients submit must match what the public fill page (Session 2) and
the customer-chart view (Session 3) will rely on. Loose validation
here means broken render later, so v1 is strict: unknown field types
rejected, required props enforced per type, choice fields require
non-empty options.
"""

from __future__ import annotations

import re

from rest_framework import serializers

from apps.services.models import Service

from .models import FormSubmission, FormTemplate, ServiceFormAssignment


# Field types supported in v1. Adding more (image upload, file
# upload, conditional logic) is a polish concern.
#
# `paragraph` is an instructional-text field (no input). It's how
# consent forms render the legal/clinical body the patient must
# read before signing — risks, alternatives, etc. The patient
# doesn't fill anything in; the renderer treats it as a styled
# block of prose. Stored as a regular schema field with `type:
# paragraph` + `label` (used as the heading) + `body` (the block
# of prose). No `required` check, no answer expected at sign time.
ALLOWED_FIELD_TYPES = frozenset({
    'short_text',
    'long_text',
    'choice_single',
    'choice_multiple',
    'date',
    'signature',
    'paragraph',
})

# Subset that ACCEPTS an answer from the patient. `paragraph` is
# the only display-only type — it never lands in the submission's
# `answers` JSON and the public-sign endpoint silently ignores any
# value submitted for it.
INPUT_FIELD_TYPES = frozenset({
    'short_text', 'long_text', 'choice_single',
    'choice_multiple', 'date', 'signature',
})

# Field id pattern — kept simple ASCII so we can use it as a JSON key
# in submission answers, a DOM id in the fill page, and a stable
# identifier across version bumps.
FIELD_ID_RE = re.compile(r'^[a-zA-Z0-9_]{1,64}$')


def _validate_field(field, index):
    """Validate a single field dict. Raises ValidationError on issues
    keyed by `fields[i]` so the operator sees which field broke."""
    if not isinstance(field, dict):
        raise serializers.ValidationError({
            f'fields[{index}]': 'Each field must be an object.',
        })
    field_id = field.get('id')
    field_type = field.get('type')
    label = field.get('label')

    if not field_id or not isinstance(field_id, str) or not FIELD_ID_RE.match(field_id):
        raise serializers.ValidationError({
            f'fields[{index}]': (
                'Each field requires an `id` (1–64 ASCII letters / digits / '
                'underscore). Generated by the builder; do not edit by hand.'
            ),
        })
    if field_type not in ALLOWED_FIELD_TYPES:
        raise serializers.ValidationError({
            f'fields[{index}]': (
                f'Unknown field type "{field_type}". Allowed: '
                f'{sorted(ALLOWED_FIELD_TYPES)}.'
            ),
        })
    if not label or not isinstance(label, str) or not label.strip():
        raise serializers.ValidationError({
            f'fields[{index}]': 'Each field requires a non-empty `label`.',
        })

    # Type-specific validation.
    if field_type in {'choice_single', 'choice_multiple'}:
        options = field.get('options')
        if not isinstance(options, list) or len(options) < 2:
            raise serializers.ValidationError({
                f'fields[{index}]': (
                    'Choice fields require at least two `options`, each with '
                    '`value` + `label`.'
                ),
            })
        seen_values = set()
        for opt_index, opt in enumerate(options):
            if not isinstance(opt, dict):
                raise serializers.ValidationError({
                    f'fields[{index}].options[{opt_index}]': 'Must be an object.',
                })
            value = opt.get('value')
            opt_label = opt.get('label')
            if not value or not isinstance(value, str):
                raise serializers.ValidationError({
                    f'fields[{index}].options[{opt_index}]': 'Requires a non-empty `value`.',
                })
            if not opt_label or not isinstance(opt_label, str):
                raise serializers.ValidationError({
                    f'fields[{index}].options[{opt_index}]': 'Requires a non-empty `label`.',
                })
            if value in seen_values:
                raise serializers.ValidationError({
                    f'fields[{index}].options[{opt_index}]': (
                        f'Duplicate option value "{value}" within this field.'
                    ),
                })
            seen_values.add(value)


class FormTemplateSerializer(serializers.ModelSerializer):
    """Read + write shape for `FormTemplate`.

    `version` is read-only — the viewset bumps it on every save
    where `schema` actually changed. `service_ids` is a write-only
    convenience field for setting which services this consent form
    applies to (full-replace semantics, mirrors the `set_location_ids`
    pattern from memberships). Read shape exposes the assigned
    service ids via the read-only `service_ids` getter.
    """

    service_ids = serializers.SerializerMethodField()
    set_service_ids = serializers.PrimaryKeyRelatedField(
        queryset=Service.objects.all(),
        many=True,
        write_only=True,
        required=False,
    )

    class Meta:
        model = FormTemplate
        fields = [
            'id',
            'name', 'description',
            'form_type', 'recurrence',
            'schema',
            'version',
            'is_active',
            'service_ids', 'set_service_ids',
            'created_at', 'updated_at',
        ]
        read_only_fields = [
            'id', 'version', 'service_ids', 'created_at', 'updated_at',
        ]

    def get_service_ids(self, obj: FormTemplate):
        return list(obj.service_assignments.values_list('service_id', flat=True))

    def validate_schema(self, value):
        if not isinstance(value, dict):
            raise serializers.ValidationError(
                'Schema must be an object with a `fields` array.',
            )
        fields = value.get('fields', [])
        if not isinstance(fields, list):
            raise serializers.ValidationError(
                '`fields` must be an array (use `[]` for an empty form template).',
            )

        # Per-field validation + duplicate-id guard.
        seen_ids: set[str] = set()
        for i, field in enumerate(fields):
            _validate_field(field, i)
            field_id = field['id']
            if field_id in seen_ids:
                raise serializers.ValidationError({
                    f'fields[{i}]': f'Duplicate field id "{field_id}".',
                })
            seen_ids.add(field_id)

        # Strip unknown top-level keys + normalize the shape so the
        # stored schema is canonical (helps versioning diffs stay
        # honest later).
        return {'fields': fields}

    def validate_set_service_ids(self, value):
        # Cross-tenant guard: every service must belong to this
        # template's tenant. The PrimaryKeyRelatedField queryset is
        # unrestricted; tenant scope is enforced here.
        from apps.tenants.context import get_current_tenant
        tenant = get_current_tenant()
        if tenant is None:
            raise serializers.ValidationError(
                'No tenant context resolved; cannot validate services.',
            )
        for service in value:
            if service.tenant_id != tenant.id:
                raise serializers.ValidationError(
                    f'Service {service.id} does not belong to this tenant.',
                )
        return value

    def validate(self, attrs):
        # Service mapping is meaningful only for consent forms.
        # Intake forms get assigned via "first appointment" rule, not
        # service mapping — silently dropping mappings on intake would
        # hide the operator's misclick. Reject explicitly.
        form_type = attrs.get('form_type') or (
            self.instance.form_type if self.instance else None
        )
        if 'set_service_ids' in attrs and form_type == FormTemplate.FormType.INTAKE:
            if attrs['set_service_ids']:
                raise serializers.ValidationError({
                    'set_service_ids': (
                        'Intake forms aren\'t mapped to services — they '
                        'auto-assign on a customer\'s first appointment ever. '
                        'Switch the form type to "consent" to map to services.'
                    ),
                })
        return attrs


# ── FormSubmission serializers ──────────────────────────────────────


class FormSubmissionListSerializer(serializers.ModelSerializer):
    """Compact representation for list views — `/api/form-submissions/`
    + nested in customer profile + appointment popover.

    Deliberately omits PHI (`answers`, `signature_data`) so the list
    payload doesn't carry medical history into surfaces that don't
    need it (front-desk staff prompting "Sarah has 2 pending forms"
    only need the status + name + token, not the answers).
    Detail endpoint exposes those behind clinical access.
    """

    template_name = serializers.CharField(source='form_template.name', read_only=True)
    template_form_type = serializers.CharField(source='form_template.form_type', read_only=True)
    customer_id = serializers.IntegerField(read_only=True)
    customer_name = serializers.CharField(source='customer.full_name', read_only=True)
    appointment_id = serializers.IntegerField(read_only=True, allow_null=True)

    class Meta:
        model = FormSubmission
        fields = [
            'id',
            'template_name', 'template_form_type',
            'template_version_at_assignment',
            'customer_id', 'customer_name',
            'appointment_id',
            'token',
            'status',
            'signed_at',
            'voided_at',
            'created_at',
        ]
        read_only_fields = fields


class FormSubmissionDetailSerializer(serializers.ModelSerializer):
    """Detail shape — includes the schema snapshot + answers +
    signature data. **PHI**; the viewset gates this behind
    `MANAGE_STAFF` (owner / manager) for v1. Refines to clinical-only
    in a future polish pass when the permission catalog supports
    it (HIPAA §164.502(b) minimum-necessary).
    """

    template_name = serializers.CharField(source='form_template.name', read_only=True)
    template_form_type = serializers.CharField(source='form_template.form_type', read_only=True)
    customer_id = serializers.IntegerField(read_only=True)
    customer_name = serializers.CharField(source='customer.full_name', read_only=True)
    appointment_id = serializers.IntegerField(read_only=True, allow_null=True)

    class Meta:
        model = FormSubmission
        fields = [
            'id',
            'template_name', 'template_form_type',
            'template_version_at_assignment', 'schema_snapshot',
            'customer_id', 'customer_name',
            'appointment_id',
            'token', 'status',
            'answers', 'signature_data',
            'signed_at', 'ip_address', 'user_agent',
            'voided_at', 'voided_reason',
            'created_at', 'updated_at',
        ]
        read_only_fields = fields


class FormSubmissionVoidSerializer(serializers.Serializer):
    """Input for `POST /api/form-submissions/{id}/void/` — operator
    voids a pending or completed submission with an explicit reason.
    Reason is required (operationally + for audit clarity)."""
    reason = serializers.CharField(min_length=1, max_length=500)


# ── Public fill flow serializers (token-based, unauthenticated) ─────


class PublicFormSubmissionSerializer(serializers.ModelSerializer):
    """Read shape for the public fill page (`GET /api/forms/sign/<token>/`).

    Returns the schema + status + (when completed) the answers — the
    same surface serves "client filling out the form" (status pending)
    and "operator viewing the signed copy via the same URL" (status
    completed). Customer name is the only customer-PHI included so
    the page can show "Hi {name}" on the fill flow.

    Tenant + customer details beyond the name are deliberately
    excluded — this endpoint is unauthenticated; minimum information
    needed for the fill flow.
    """

    template_name = serializers.CharField(source='form_template.name', read_only=True)
    customer_first_name = serializers.CharField(source='customer.first_name', read_only=True)

    class Meta:
        model = FormSubmission
        fields = [
            'token',
            'template_name',
            'template_version_at_assignment',
            'schema_snapshot',
            'customer_first_name',
            'status',
            'answers',
            'signed_at',
        ]
        read_only_fields = fields


class PublicFormSignSerializer(serializers.Serializer):
    """Input for `POST /api/forms/sign/<token>/` — the client submits
    answers + signature canvas data.

    `answers` keyed by field id from the schema snapshot. Validation
    against the schema (required fields populated, choice values
    matching options, etc.) happens in the view because it depends
    on the snapshot loaded from the submission.

    `signature_data` is a base64-encoded PNG (data URL prefix accepted
    + stripped). Required — there's no consent flow without a
    signature.
    """

    answers = serializers.JSONField()
    signature_data = serializers.CharField(min_length=1, max_length=2_000_000)

    def validate_answers(self, value):
        if not isinstance(value, dict):
            raise serializers.ValidationError(
                'Answers must be a JSON object keyed by field id.',
            )
        return value
