# Generated by Django 5.1.15 on 2026-05-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_line1_user_address_line2_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_platform_admin',
            field=models.BooleanField(default=False, help_text='Lumè-the-platform staff. Authenticates via /api/auth/platform/login/ and accesses /platform/*. Must have zero TenantMembership rows — platform admins and tenant users are disjoint.'),
        ),
    ]
