# Generated by Django 5.1.15 on 2026-05-15 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_email_marketing_consent_at_and_more'),
        ('tenants', '0011_tenant_twilio_from_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound (staff → customer)'), ('inbound', 'Inbound (customer → staff)')], db_index=True, max_length=10)),
                ('body', models.TextField(help_text='The SMS body. PHI — every read is audit-logged.')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('received', 'Received (inbound)')], db_index=True, default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', help_text='Twilio Message SID. Empty for stub-mode dev sends.', max_length=64)),
                ('from_number', models.CharField(blank=True, default='', max_length=20)),
                ('to_number', models.CharField(blank=True, default='', max_length=20)),
                ('media_urls', models.TextField(blank=True, default='', help_text='Newline-separated list of MMS media URLs hosted on Twilio.')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(help_text="The customer this conversation is with. PROTECT so we don't lose message history when a customer is soft-deleted; the audit trail outlives the customer row.", on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='customers.customer')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Staff member who composed the outbound message. Null for inbound.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'customer', '-created_at'], name='messaging_m_tenant__423339_idx'), models.Index(fields=['tenant', 'direction', '-created_at'], name='messaging_m_tenant__69f738_idx')],
            },
        ),
    ]
