# Generated by Django 5.1.15 on 2026-05-15 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('tenants', '0011_tenant_twilio_from_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short label shown in the picker (e.g. "Address" or "Running late?"). Operators identify replies by name, not by reading the body each time.', max_length=80)),
                ('body', models.TextField(help_text='The text inserted into the composer.', max_length=1600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Author. Null when the user is removed later.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='savedreply_tenant_name_unique')],
            },
        ),
    ]
