# Generated by Django 5.1.15 on 2026-05-15 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_savedreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('manual', 'Manual (operator-typed)'), ('confirmation', 'Appointment confirmation (automated)'), ('reminder', 'Appointment reminder (automated)'), ('review_request', 'Review request (automated)')], db_index=True, default='manual', help_text='What triggered the send. Manual = staff typed it in the inbox; the other three are automated transactional SMS mirrored into the thread so the operator can see what the customer saw.', max_length=20),
        ),
    ]
