# Generated by Django 5.1.15 on 2026-05-04 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_add_referral_code'),
        ('services', '0003_add_code_tax_type'),
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_date', models.DateField(help_text='The day the customer originally wanted. Operators use this as the starting point when looking for an opening — flex around it as needed.')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional message from the customer ("mornings preferred", "available any time before June"). Plain text.')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('declined', 'Declined')], db_index=True, default='waiting', max_length=20)),
                ('source', models.CharField(blank=True, default='', help_text="e.g. 'online' (public booking page), 'staff' (operator-added)", max_length=50)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('booked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='customers.customer')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='tenants.location')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='tenants.tenantmembership')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='waitlist_entries', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'preferred_date'], name='waitlist_wa_tenant__04aa3a_idx'), models.Index(fields=['tenant', 'customer', '-created_at'], name='waitlist_wa_tenant__03c235_idx')],
            },
        ),
    ]
