# Generated by Django 5.1.15 on 2026-05-05 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0005_add_booking_token'),
        ('customers', '0003_customer_email_marketing_consent_at_and_more'),
        ('invoices', '0004_invoicelineitem_product_and_more'),
        ('services', '0003_add_code_tax_type'),
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Short identifier. Auto-generated from the name on first save; editable. Unique within the tenant.', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='All-in package price. Snapshotted onto the invoice line.')),
                ('tax_rate_percent', models.DecimalField(decimal_places=3, default=0, help_text='Tax rate as a percent. Whether to tax packages varies by jurisdiction; default 0 lets each tenant set per-package.', max_digits=6)),
                ('validity_days', models.PositiveIntegerField(blank=True, help_text='Days from purchase before unredeemed credits expire. Null = never expires.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive packages stay on past invoices but cannot be sold on new invoices.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Credits granted for this service when the package is sold.')),
                ('sort_order', models.IntegerField(default=0)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages.package')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(default=0)),
                ('validity_days', models.PositiveIntegerField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(blank=True, help_text='Set when the source invoice closes (status flips PENDING→ACTIVE).', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Computed at purchase time: purchased_at + validity_days.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('voided', 'Voided')], db_index=True, default='pending', max_length=20)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchased_packages', to='customers.customer')),
                ('source_invoice_line', models.OneToOneField(help_text='The invoice line that paid for this package.', on_delete=django.db.models.deletion.PROTECT, related_name='purchased_package', to='invoices.invoicelineitem')),
                ('source_template', models.ForeignKey(blank=True, help_text='Catalog package this was bought from. Null for custom one-off packages built per-customer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='packages.package')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasedPackageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('quantity_purchased', models.PositiveIntegerField()),
                ('quantity_remaining', models.PositiveIntegerField()),
                ('unit_value_cents', models.PositiveIntegerField(default=0, help_text='Snapshot of the service\'s a-la-carte price at purchase time. Used as the credit value at redemption (the redemption invoice line is created at this price with a 100% discount, so reports show "$200 service paid for via package").')),
                ('sort_order', models.IntegerField(default=0)),
                ('purchased_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='packages.purchasedpackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PackageRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Signed: positive for a normal redeem, negative for a reversal. Net of all rows across an item must equal (quantity_purchased − quantity_remaining).')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='package_redemptions', to='appointments.appointment')),
                ('by_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invoice_line', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='invoices.invoicelineitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('purchased_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='packages.purchasedpackage')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='packages.purchasedpackageitem')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['tenant', 'is_active', 'name'], name='packages_pa_tenant__d35920_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['tenant', 'sku'], name='packages_pa_tenant__0633d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('tenant', 'sku'), name='packages_unique_tenant_sku'),
        ),
        migrations.AddConstraint(
            model_name='packageitem',
            constraint=models.UniqueConstraint(fields=('package', 'service'), name='package_items_unique_package_service'),
        ),
        migrations.AddConstraint(
            model_name='packageitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='package_items_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='purchasedpackage',
            index=models.Index(fields=['tenant', 'customer', 'status'], name='packages_pu_tenant__d6cda6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasedpackage',
            index=models.Index(fields=['tenant', 'status', 'expires_at'], name='packages_pu_tenant__334658_idx'),
        ),
        migrations.AddConstraint(
            model_name='purchasedpackageitem',
            constraint=models.UniqueConstraint(fields=('purchased_package', 'service'), name='purchased_package_items_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchasedpackageitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_remaining__lte', models.F('quantity_purchased'))), name='purchased_package_items_remaining_lte_purchased'),
        ),
        migrations.AddIndex(
            model_name='packageredemption',
            index=models.Index(fields=['tenant', 'purchased_package', '-redeemed_at'], name='packages_pa_tenant__eb859a_idx'),
        ),
        migrations.AddConstraint(
            model_name='packageredemption',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='package_redemptions_quantity_nonzero'),
        ),
    ]
