# Generated by Django 5.1.15 on 2026-05-17 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_gift_card_credits_cents_and_more'),
        ('packages', '0001_initial'),
        ('services', '0005_service_provenance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedpackage',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='external_invoice_no',
            field=models.CharField(blank=True, help_text="Upstream invoice / receipt number — the operator's link back to the original system when researching a balance.", max_length=100),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='external_source',
            field=models.CharField(blank=True, help_text="e.g. 'zenoti', 'vagaro'", max_length=50),
        ),
        migrations.AddField(
            model_name='purchasedpackage',
            name='imported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasedpackage',
            name='source_invoice_line',
            field=models.OneToOneField(blank=True, help_text='The Lumè invoice line that paid for this package. NULL for rows created by a migration importer (e.g. Zenoti) — the upstream proof-of-payment lives in `external_invoice_no` instead.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchased_package', to='invoices.invoicelineitem'),
        ),
        migrations.AlterField(
            model_name='purchasedpackageitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='FK to the catalog Service. NULL for migration-imported rows where the upstream service name did not match any Lumè Service in the catalog — the snapshot `service_name` still displays on the customer profile so the operator can manually map / redeem it after the fact.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service'),
        ),
    ]
