# Generated by Django 5.1.15 on 2026-05-07 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in_at', models.DateTimeField(db_index=True, help_text='When the shift started.')),
                ('clock_out_at', models.DateTimeField(blank=True, db_index=True, help_text='When the shift ended. Null while the shift is open.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional note (e.g. "covered for Sarah", "left early").')),
                ('source', models.CharField(choices=[('self', 'Self'), ('front_desk', 'Front desk'), ('kiosk', 'Kiosk'), ('manual', 'Manually added')], default='self', help_text='How this punch was recorded.', max_length=20)),
                ('edited_at', models.DateTimeField(blank=True, help_text='Set when an entry is edited after the punch (manager correction).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(help_text='The employee whose shift this is.', on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='tenants.tenantmembership')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-clock_in_at'],
                'indexes': [models.Index(fields=['tenant', 'membership', '-clock_in_at'], name='timetrackin_tenant__7a8bb8_idx'), models.Index(fields=['tenant', 'clock_out_at'], name='timetracking_open_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('clock_out_at__isnull', True), ('clock_out_at__gt', models.F('clock_in_at')), _connector='OR'), name='time_entries_clock_out_after_clock_in')],
            },
        ),
    ]
