# Generated by Django 5.1.15 on 2026-05-03 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_add_code_tax_type'),
        ('tenants', '0008_providerschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Operator-facing label, e.g. "New client intake" or "Botox consent v3".', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Internal notes about when to use this form. Not shown to clients.')),
                ('form_type', models.CharField(choices=[('intake', 'Intake'), ('consent', 'Consent')], max_length=20)),
                ('recurrence', models.CharField(choices=[('once', 'Once per customer'), ('per_visit', 'Every visit')], default='per_visit', help_text='How often a customer must (re)sign. "Once" = sign once forever (typical for intake). "Every visit" = sign each appointment that triggers the form (typical for clinical consent).', max_length=20)),
                ('schema', models.JSONField(default=dict, help_text='Field definitions: {"fields": [{"id": "...", "type": "short_text", "label": "...", "required": true, ...}]}. Shape validated by the serializer.')),
                ('version', models.PositiveIntegerField(default=1, help_text='Auto-incremented when the schema changes. Submissions (Session 2) snapshot the version they were signed against so historical records stay legible after the template evolves.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates stop auto-assigning to new appointments. Existing pending + completed submissions are unaffected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['form_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFormAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('form_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_assignments', to='forms.formtemplate')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_assignments', to='services.service')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['form_template', 'service'],
            },
        ),
        migrations.AddIndex(
            model_name='formtemplate',
            index=models.Index(fields=['tenant', 'form_type', 'is_active'], name='forms_formt_tenant__933e89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceformassignment',
            unique_together={('form_template', 'service')},
        ),
    ]
