# Generated by Django 5.1.15 on 2026-05-03 12:25

import apps.forms.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_location_required'),
        ('customers', '0002_add_referral_code'),
        ('forms', '0001_initial'),
        ('tenants', '0008_providerschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_version_at_assignment', models.PositiveIntegerField(help_text='Snapshot of `FormTemplate.version` at assignment time, for audit + display.')),
                ('schema_snapshot', models.JSONField(help_text="Snapshot of the template's `schema` at assignment time. The fill page renders from this, never from the live template — protects in-flight pending submissions from template edits, and protects signed submissions from being re-rendered as a different shape.")),
                ('token', models.CharField(db_index=True, default=apps.forms.models._generate_submission_token, help_text='High-entropy public token (~256 bits via secrets.token_urlsafe). Bearer credential for the public fill page — anyone with the URL can fill the form. Generated server-side on submission create.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending signature'), ('completed', 'Completed'), ('voided', 'Voided')], db_index=True, default='pending', max_length=20)),
                ('answers', models.JSONField(default=dict, help_text='Filled answers keyed by field id from the schema snapshot. PHI — gated behind VIEW_CLIENT_PHI on the detail endpoint.')),
                ('signature_data', models.TextField(blank=True, help_text="Base64-encoded PNG of the client's canvas signature. PHI. Empty until status transitions to completed.")),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address that submitted the signature. Captured for audit.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user-agent string at time of signing. Captured for audit.')),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('voided_reason', models.TextField(blank=True, help_text='Operator-supplied reason for voiding. Required at the API level.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, help_text="Appointment that triggered this submission. Null for intake forms (those are per-customer, not per-appointment — but the trigger is still the customer's first appointment ever).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='form_submissions', to='appointments.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='form_submissions', to='customers.customer')),
                ('form_template', models.ForeignKey(help_text='Template this submission was generated from. PROTECT — submissions outlive template retirement.', on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms.formtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_form_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'customer', 'status'], name='forms_forms_tenant__e9e444_idx'), models.Index(fields=['tenant', 'appointment', 'status'], name='forms_forms_tenant__a57452_idx')],
            },
        ),
    ]
