"""Invoicing models.

The `Invoice` model is the single source of truth for "money was collected
for a delivered service." Per ADR 0007, closing an invoice is the only
code path that can transition an `Appointment` to `COMPLETED`; reopening
within 60 days reverts the appointment to `CHECKED_IN`.

Money handling rules:

  - All monetary values stored as `PositiveIntegerField` cents. No floats
    in the money path, ever.
  - Tax computed at line level using `Decimal` arithmetic with
    `ROUND_HALF_UP` for predictability (matches what a customer expects
    from invoice math; banker's rounding produces 1¢ deltas in
    common cases).
  - Invoice totals (`subtotal_cents`, `tax_cents`, `total_cents`) are
    denormalized for query speed but always recomputed from the line
    items inside `Invoice.recalculate_totals()`. A `CheckConstraint`
    enforces `total_cents = subtotal_cents + tax_cents` at the DB so a
    bug in application code can't quietly persist an inconsistent total.
  - Line item prices are snapshotted from the service at the time the
    line is created. A future change to `Service.price_cents` does not
    alter historical invoices.

Concurrency rules:

  - State-changing methods (`close`, `reopen`, `void`) use
    `transaction.atomic` plus `select_for_update()` on the invoice row,
    re-reading `status` after the lock to defeat lost-update races.
    They also lock the linked appointment row when transitioning it.

Audit rules (SOC 2 CC7.2):

  - Every state-changing method writes a structured `AuditLog` entry via
    `apps.audit.services.record`. The metadata captures the transition
    (`open→paid`, `paid→open`, etc.) and any user-supplied reason so the
    immutable trail tells "who, when, what, why."

The `REOPEN_WINDOW_DAYS = 60` constant is the user's explicit business
rule (ADR 0007). Tightening to 30 days is a one-line change and a
migration is not required because the value is computed from
`closed_at` at request time, not stored on the row.
"""

from __future__ import annotations

import datetime as dt
from decimal import ROUND_HALF_UP, Decimal

from django.conf import settings
from django.db import models, transaction
from django.utils import timezone

from apps.tenants.abstract_models import TenantedModel


# ── Money helpers ────────────────────────────────────────────────────────


def compute_line_tax_cents(
    line_subtotal_cents: int,
    tax_rate_percent: Decimal | float | int,
) -> int:
    """Compute line tax in cents using ROUND_HALF_UP.

    Returns 0 for a zero or null tax rate. Performs the multiplication in
    `Decimal` so the result is independent of binary-float rounding
    quirks. Result is `int` cents.
    """
    if not tax_rate_percent:
        return 0
    rate = Decimal(str(tax_rate_percent))
    if rate <= 0:
        return 0
    sub = Decimal(line_subtotal_cents)
    tax = (sub * rate / Decimal(100)).quantize(Decimal('1'), rounding=ROUND_HALF_UP)
    return int(tax)


# ── Invoice ──────────────────────────────────────────────────────────────


class Invoice(TenantedModel):
    """A billing record. Created automatically per appointment; standalone
    when `appointment` is null (Phase 2A POS).

    The `status` field is the state machine:

        OPEN ── close() ─► PAID ── reopen() ─► OPEN  (≤ 60 days)
         │
         └── void() ─► VOID  (terminal)

    Status transitions are guarded by `close()`, `reopen()`, `void()` —
    do not write to `status` directly. The methods take the row lock and
    recheck invariants; assignments outside them bypass the audit trail
    and the appointment-side coordination.
    """

    REOPEN_WINDOW_DAYS = 60

    class Status(models.TextChoices):
        OPEN = 'open', 'Open'
        PAID = 'paid', 'Paid'
        VOID = 'void', 'Void'

    class PaymentMethod(models.TextChoices):
        # v1 supports cash / check / external card terminal +
        # gift_card (used when applied gift card credits cover the
        # entire invoice — i.e. amount_due_cents == 0). Real
        # processor integration lands in Phase 2A; we'll add a
        # CARD_PROCESSED choice + transaction_id then.
        CASH = 'cash', 'Cash'
        CHECK = 'check', 'Check'
        CARD_EXTERNAL = 'card_external', 'Card (external terminal)'
        GIFT_CARD = 'gift_card', 'Gift card (full coverage)'
        OTHER = 'other', 'Other'

    # Human-readable invoice number, format `INV-YYYY-NNNN`. Per-tenant
    # sequential, year-prefixed, resets on Jan 1. Unique within the
    # tenant (enforced by `Meta.constraints` below). Generated by
    # `apps.invoices.services.generate_invoice_number(tenant)` and
    # assigned in the appointment-creation signal — see signals.py.
    #
    # blank='' on creation lets the row exist briefly before the
    # number is assigned in the same transaction; the unique
    # constraint is partial (excludes empty strings) so the brief
    # blank state doesn't collide.
    invoice_number = models.CharField(
        max_length=20,
        blank=True,
        default='',
        db_index=True,
        help_text=(
            'Human-readable invoice number, format INV-YYYY-NNNN. '
            'Per-tenant sequential, resets each calendar year.'
        ),
    )

    customer = models.ForeignKey(
        'customers.Customer',
        on_delete=models.PROTECT,
        related_name='invoices',
    )
    appointment = models.OneToOneField(
        'appointments.Appointment',
        on_delete=models.PROTECT,
        related_name='invoice',
        null=True,
        blank=True,
        help_text=(
            'The appointment this invoice bills. Null for standalone '
            'invoices (POS, packages, gift cards). One-to-one because '
            '"all appointments are an invoice" per ADR 0007.'
        ),
    )

    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.OPEN,
        db_index=True,
    )

    # Money. All in cents. Recomputed from line items.
    subtotal_cents = models.PositiveIntegerField(default=0)
    tax_cents = models.PositiveIntegerField(default=0)
    total_cents = models.PositiveIntegerField(default=0)

    # Discount fields. Two layers stacked: each `InvoiceLineItem` can
    # carry its own per-line discount; this header carries an additional
    # invoice-level discount that's distributed pro-rata across the
    # already-line-discounted lines by `recalculate_totals`.
    #
    # `*_kind` is the operator's choice ('amount' or 'percent'); `*_input`
    # is the typed value (e.g. 10.00 = $10 off OR 10% off depending on
    # kind); `*_cents` is the derived cents that actually came off the
    # invoice. `_reason` is an optional free-form note surfaced on the
    # printed invoice and in the audit log so financial review can
    # answer "why was this $20 taken off?". Owner / Manager edit the
    # discount directly; everyone else needs a manager-override on the
    # API call (validated against the tenant's owner / manager roster).

    class InvoiceDiscountKind(models.TextChoices):
        AMOUNT = 'amount', 'Amount off ($)'
        PERCENT = 'percent', 'Percent off (%)'

    invoice_discount_kind = models.CharField(
        max_length=10,
        choices=InvoiceDiscountKind.choices,
        default=InvoiceDiscountKind.AMOUNT,
    )
    invoice_discount_input = models.DecimalField(
        max_digits=8, decimal_places=2, default=0,
        help_text=(
            "Operator-typed value. For 'amount' kind: dollars off "
            "(5.00 = $5). For 'percent' kind: percent off (10.00 = 10%)."
        ),
    )
    invoice_discount_cents = models.PositiveIntegerField(
        default=0,
        help_text=(
            'Derived cents knocked off the invoice. Computed by '
            '`recalculate_totals` from kind + input + line basis, '
            'capped at the after-line-discount basis (never below $0).'
        ),
    )
    invoice_discount_reason = models.CharField(
        max_length=200, blank=True, default='',
    )

    # Denormalized aggregate of all line-level discounts on this invoice.
    # Stored so the DB-level "subtotal − discounts + tax = total"
    # constraint can verify the rollup without aggregating across rows.
    line_discounts_total_cents = models.PositiveIntegerField(default=0)

    # Gift card credits applied as a payment toward this invoice.
    # Mutated by the apply-gift-card / reverse-gift-card-redemption
    # actions; reduces the residual `amount_due_cents` paid via
    # `payment_method`. Stored on the invoice header (not as a line
    # item) because it's a payment-tender, not a billable line.
    gift_card_credits_cents = models.PositiveIntegerField(
        default=0,
        help_text=(
            'Total of gift card balances applied toward this invoice. '
            'Reduces amount_due_cents (which is what payment_method '
            'covers at close).'
        ),
    )

    # Payment record. Populated on close().
    payment_method = models.CharField(
        max_length=20,
        choices=PaymentMethod.choices,
        blank=True,
    )
    payment_reference = models.CharField(
        max_length=100,
        blank=True,
        help_text=(
            'Free-form: cash drawer #, check #, last 4 of card, etc. '
            'Real card-processor transaction IDs land in Phase 2A.'
        ),
    )

    notes = models.TextField(blank=True, help_text='Internal staff notes.')

    # Audit fields. Each who/when pair captures a state transition for
    # SOC 2 traceability. `closed_at` is set on the FIRST close and never
    # updated; `reopen_count` increments on each reopen. The 60-day reopen
    # window is computed from `closed_at` so re-closes don't extend it.
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='invoices_created',
    )
    closed_at = models.DateTimeField(null=True, blank=True)
    closed_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='invoices_closed',
    )
    reopened_at = models.DateTimeField(null=True, blank=True)
    reopened_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='invoices_reopened',
    )
    reopen_count = models.PositiveIntegerField(default=0)
    voided_at = models.DateTimeField(null=True, blank=True)
    voided_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='invoices_voided',
    )
    void_reason = models.CharField(max_length=200, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['tenant', 'customer', '-created_at']),
            models.Index(fields=['tenant', 'status', '-created_at']),
            models.Index(fields=['tenant', 'closed_at']),
        ]
        constraints = [
            # SOC 2 PI1.1 — data integrity: a stored total can never
            # disagree with its parts. If a code path tries to write an
            # inconsistent row, the DB rejects it. With discounts the
            # math is:
            #   total = subtotal − line_discounts − invoice_discount + tax
            # `subtotal_cents` stays the pre-discount sum of
            # `line_subtotal_cents` (so reports that have always read it
            # as "gross sales" don't shift meaning). The line + invoice
            # discount fields capture the deductions; `total_cents` is
            # the post-discount, post-tax customer charge.
            models.CheckConstraint(
                condition=models.Q(
                    total_cents=(
                        models.F('subtotal_cents')
                        - models.F('line_discounts_total_cents')
                        - models.F('invoice_discount_cents')
                        + models.F('tax_cents')
                    ),
                ),
                name='invoices_total_equals_subtotal_minus_discounts_plus_tax',
            ),
            # PAID requires a closed_at timestamp. OPEN may or may not
            # have one (after a reopen, status=OPEN with closed_at set).
            models.CheckConstraint(
                condition=(
                    ~models.Q(status='paid')
                    | models.Q(closed_at__isnull=False)
                ),
                name='invoices_paid_requires_closed_at',
            ),
            # VOID requires voided_at; non-VOID has voided_at NULL.
            models.CheckConstraint(
                condition=(
                    models.Q(status='void', voided_at__isnull=False)
                    | (~models.Q(status='void') & models.Q(voided_at__isnull=True))
                ),
                name='invoices_void_requires_voided_at',
            ),
            # Invoice number is unique within a tenant. Partial
            # constraint: empty strings (`default=''` rows that haven't
            # had a number assigned yet) are excluded so a brief
            # blank-during-creation state doesn't trigger collisions.
            # Once `generate_invoice_number` runs every row has a
            # value and the constraint is fully effective.
            models.UniqueConstraint(
                fields=['tenant', 'invoice_number'],
                condition=~models.Q(invoice_number=''),
                name='invoices_invoice_number_unique_per_tenant',
            ),
        ]

    def __str__(self):
        return f'Invoice #{self.pk} · {self.customer.full_name} · {self.get_status_display()}'

    # ── Derived state ────────────────────────────────────────────────────

    @property
    def reopen_deadline(self):
        """Datetime after which reopen is no longer allowed.

        `None` if the invoice has never been closed. Computed from
        `closed_at` (the FIRST close); re-closes after a reopen do not
        extend the window.
        """
        if not self.closed_at:
            return None
        return self.closed_at + dt.timedelta(days=self.REOPEN_WINDOW_DAYS)

    @property
    def is_reopen_window_open(self) -> bool:
        """Whether the 60-day reopen window is still open."""
        deadline = self.reopen_deadline
        return bool(deadline and timezone.now() <= deadline)

    @property
    def amount_due_cents(self) -> int:
        """What the customer still owes after gift card credits.

        `payment_method` at close covers exactly this amount (or 0
        if gift cards covered everything). Clamped to 0 if a buggy
        flow over-applied gift cards.
        """
        return max(0, self.total_cents - self.gift_card_credits_cents)

    # ── Money recompute ──────────────────────────────────────────────────

    def recalculate_totals(self, save: bool = True) -> None:
        """Recompute the full money rollup from the current line items,
        including pro-rata distribution of the invoice-level discount.

        Called automatically by `InvoiceLineItem.save()` and whenever
        an invoice-level discount is changed. The DB-level
        CheckConstraint (`total = subtotal − line_discounts −
        invoice_discount + tax`) is the final backstop.

        Cascade safety: per-line updates use `QuerySet.update()` —
        skipping `save()` — so we never re-enter the line save path
        that triggered us.

        Math:
          1. Pull each line's (subtotal, per-line discount, tax_rate).
          2. Compute the after-line-discount basis per line:
                line_basis = max(0, subtotal − line_discount)
          3. Compute total invoice-level discount cents from
             `invoice_discount_kind` + `invoice_discount_input`,
             capped at sum(line_basis).
          4. Distribute that across lines pro-rata on `line_basis`,
             absorbing the rounding remainder on the largest line so
             the per-line shares sum exactly to the invoice total.
          5. Recompute each line's tax on
                taxable = max(0, line_basis − invoice_share)
          6. Write back per-line `invoice_discount_share_cents` +
             `line_tax_cents` via `.update()`.
          7. Roll up `subtotal_cents`, `line_discounts_total_cents`,
             `invoice_discount_cents`, `tax_cents`, `total_cents` on
             the invoice header.
        """
        from decimal import ROUND_HALF_UP, Decimal

        # Always pull lines via an explicit queryset, NOT
        # `self.line_items.all()`. The reverse manager returns the
        # `prefetch_related('line_items')` cache when the viewset has
        # prefetched it — and our caller may have just inserted a new
        # line (`InvoiceLineItem.save()` calls us right after super().save).
        # The prefetch cache wouldn't see that new line, and recalc
        # would skip it, leaving the header totals stale.
        lines = list(
            InvoiceLineItem.objects.filter(invoice=self).order_by('id'),
        )
        if not lines:
            self.subtotal_cents = 0
            self.line_discounts_total_cents = 0
            self.invoice_discount_cents = 0
            self.tax_cents = 0
            self.total_cents = 0
            if save:
                super().save(update_fields=[
                    'subtotal_cents', 'line_discounts_total_cents',
                    'invoice_discount_cents', 'tax_cents',
                    'total_cents', 'updated_at',
                ])
            return

        # Step 1-2: per-line basis after the line's own discount.
        line_bases = [
            max(0, ln.line_subtotal_cents - ln.discount_cents)
            for ln in lines
        ]
        total_basis = sum(line_bases)

        # Step 3: target invoice-level discount in cents.
        if self.invoice_discount_input and self.invoice_discount_input > 0:
            if self.invoice_discount_kind == self.InvoiceDiscountKind.PERCENT:
                pct = Decimal(self.invoice_discount_input)
                invoice_disc_cents = int(
                    (Decimal(total_basis) * pct / Decimal(100))
                    .quantize(Decimal('1'), rounding=ROUND_HALF_UP),
                )
            else:
                invoice_disc_cents = int(Decimal(self.invoice_discount_input) * 100)
        else:
            invoice_disc_cents = 0
        invoice_disc_cents = min(max(0, invoice_disc_cents), total_basis)

        # Step 4: pro-rata distribution across lines on line_basis. We
        # floor-divide the natural share, then absorb the rounding
        # remainder on whichever line carries the largest basis so the
        # per-line shares sum to exactly `invoice_disc_cents`.
        shares = [0] * len(lines)
        if invoice_disc_cents > 0 and total_basis > 0:
            for i, basis in enumerate(line_bases):
                shares[i] = (basis * invoice_disc_cents) // total_basis
            remainder = invoice_disc_cents - sum(shares)
            if remainder != 0:
                # Largest-basis line absorbs the leftover. Ties go to
                # the first occurrence — deterministic per-line ordering
                # (Meta.ordering = ['id']) keeps recomputes stable.
                largest_idx = max(
                    range(len(lines)), key=lambda j: line_bases[j],
                )
                # Clamp so a stray +1 / −1 can't push us past basis.
                shares[largest_idx] = max(
                    0,
                    min(line_bases[largest_idx], shares[largest_idx] + remainder),
                )

        # Step 5-6: recompute tax + write per-line shares + line tax.
        new_line_taxes = [0] * len(lines)
        for i, ln in enumerate(lines):
            taxable = max(0, line_bases[i] - shares[i])
            new_line_taxes[i] = compute_line_tax_cents(taxable, ln.tax_rate_percent)
            # Skip save() — uses QuerySet.update() to avoid re-entry.
            type(ln).objects.filter(pk=ln.pk).update(
                invoice_discount_share_cents=shares[i],
                line_tax_cents=new_line_taxes[i],
            )

        # Step 7: roll up to the invoice header.
        self.subtotal_cents = sum(ln.line_subtotal_cents for ln in lines)
        self.line_discounts_total_cents = sum(ln.discount_cents for ln in lines)
        self.invoice_discount_cents = invoice_disc_cents
        self.tax_cents = sum(new_line_taxes)
        self.total_cents = (
            self.subtotal_cents
            - self.line_discounts_total_cents
            - self.invoice_discount_cents
            + self.tax_cents
        )
        if save:
            super().save(update_fields=[
                'subtotal_cents', 'line_discounts_total_cents',
                'invoice_discount_cents', 'tax_cents',
                'total_cents', 'updated_at',
            ])

    # ── Inventory side effects ───────────────────────────────────────────

    def _apply_inventory_delta(self, *, sign: int) -> list[dict]:
        """Apply a stock delta to every product line on this invoice.

        `sign=-1` is a decrement (sale at close-time), `sign=+1` is a
        restock (reopen / void). Lines whose product has
        `track_inventory=False` are skipped silently. Concurrent close
        calls across two invoices that share a product are serialized
        by `select_for_update` on the Product row.

        Returns a list of `{product_id, sku, before, after, qty}` dicts
        for audit-log metadata so the caller can attach the snapshot
        to its own audit row.

        Caller MUST already be inside a transaction. The Invoice
        state-transition methods provide that wrap.
        """
        if sign not in (-1, 1):
            raise ValueError('sign must be -1 or +1')
        # Late import — products app references back via FK.
        from apps.products.models import Product

        # Stable order makes audit logs deterministic across runs.
        product_lines = (
            self.line_items
            .select_related('product')
            .filter(product__isnull=False)
            .order_by('id')
        )
        snapshots: list[dict] = []
        for line in product_lines:
            product = line.product
            if product is None or not product.track_inventory:
                continue
            locked = (
                Product.objects.select_for_update()
                .get(pk=product.pk)
            )
            before = locked.stock_quantity
            delta = sign * line.quantity
            locked.stock_quantity = before + delta
            locked.save(update_fields=['stock_quantity', 'updated_at'])
            snapshots.append({
                'product_id': locked.pk,
                'sku': locked.sku,
                'before': before,
                'after': locked.stock_quantity,
                'qty': line.quantity,
            })
        return snapshots

    # ── Package lifecycle side effects ───────────────────────────────────

    def _activate_pending_packages(self) -> list[dict]:
        """When the invoice closes, flip every PurchasedPackage tied to
        a line on this invoice from PENDING → ACTIVE, set
        `purchased_at = now`, and compute `expires_at` from
        `validity_days` (null = no expiration).

        Returns a list of `{purchased_package_id, name}` dicts for the
        audit-log snapshot. Caller is already inside a transaction.
        """
        from datetime import timedelta
        from apps.packages.models import PurchasedPackage

        now = timezone.now()
        pending = (
            PurchasedPackage.objects
            .select_for_update()
            .filter(
                source_invoice_line__invoice=self,
                status=PurchasedPackage.Status.PENDING,
            )
        )
        snapshots: list[dict] = []
        for pp in pending:
            pp.purchased_at = now
            if pp.validity_days:
                pp.expires_at = now + timedelta(days=pp.validity_days)
            pp.status = PurchasedPackage.Status.ACTIVE
            pp.save(update_fields=[
                'purchased_at', 'expires_at', 'status', 'updated_at',
            ])
            snapshots.append({
                'purchased_package_id': pp.pk,
                'name': pp.name,
                'expires_at': pp.expires_at.isoformat() if pp.expires_at else None,
            })
        return snapshots

    def _revert_active_packages_on_reopen(self) -> list[dict]:
        """On reopen, flip every PurchasedPackage tied to this invoice
        from ACTIVE back to PENDING. Refuses (raises InvoiceStateError)
        if any of those packages have a redemption ledger entry — the
        sale already produced downstream side effects that can't be
        cleanly unwound. Operator must reopen+un-redeem manually.

        Caller is already inside a transaction.
        """
        from apps.packages.models import PackageRedemption, PurchasedPackage

        active = list(
            PurchasedPackage.objects
            .select_for_update()
            .filter(
                source_invoice_line__invoice=self,
                status=PurchasedPackage.Status.ACTIVE,
            )
        )
        if not active:
            return []
        # Refuse if any of these packages have already been drawn
        # against. Reversing redemptions out from under the customer
        # would orphan the ledger.
        redemption_count = PackageRedemption.objects.filter(
            purchased_package__in=active,
        ).count()
        if redemption_count > 0:
            raise InvoiceStateError(
                'Cannot reopen this invoice: a package on it has already '
                'been redeemed against. Reverse the redemption(s) first.',
            )
        snapshots: list[dict] = []
        for pp in active:
            pp.status = PurchasedPackage.Status.PENDING
            pp.purchased_at = None
            pp.expires_at = None
            pp.save(update_fields=[
                'status', 'purchased_at', 'expires_at', 'updated_at',
            ])
            snapshots.append({
                'purchased_package_id': pp.pk,
                'name': pp.name,
            })
        return snapshots

    def _void_pending_packages(self) -> list[dict]:
        """On invoice void, mark any PENDING PurchasedPackage tied to
        this invoice as VOIDED (the customer never paid for them)."""
        from apps.packages.models import PurchasedPackage

        pending = list(
            PurchasedPackage.objects
            .select_for_update()
            .filter(
                source_invoice_line__invoice=self,
                status=PurchasedPackage.Status.PENDING,
            )
        )
        snapshots: list[dict] = []
        now = timezone.now()
        for pp in pending:
            pp.status = PurchasedPackage.Status.VOIDED
            pp.voided_at = now
            pp.void_reason = 'invoice_voided'
            pp.save(update_fields=[
                'status', 'voided_at', 'void_reason', 'updated_at',
            ])
            snapshots.append({
                'purchased_package_id': pp.pk,
                'name': pp.name,
            })
        return snapshots

    # ── Subscription (membership) lifecycle side effects ─────────────────

    def _activate_pending_subscriptions(self) -> list[dict]:
        """When the invoice closes, flip every Subscription tied to
        a line on this invoice from PENDING → ACTIVE, set
        `started_at = now`, and compute the period bounds from
        `cycle_days` on the snapshot.

        Returns a list of `{subscription_id, name, period_ends_at}`
        dicts for the audit-log snapshot. Caller is already inside
        a transaction.
        """
        from datetime import timedelta
        from apps.memberships.models import MembershipPlan, Subscription

        now = timezone.now()
        pending = (
            Subscription.objects
            .select_for_update()
            .filter(
                source_invoice_line__invoice=self,
                status=Subscription.Status.PENDING,
            )
        )
        snapshots: list[dict] = []
        for sub in pending:
            cycle_days = (
                365 if sub.billing_interval ==
                MembershipPlan.BillingInterval.ANNUAL else 30
            )
            sub.started_at = now
            sub.current_period_starts_at = now
            sub.current_period_ends_at = now + timedelta(days=cycle_days)
            sub.status = Subscription.Status.ACTIVE
            sub.save(update_fields=[
                'started_at', 'current_period_starts_at',
                'current_period_ends_at', 'status', 'updated_at',
            ])
            snapshots.append({
                'subscription_id': sub.pk,
                'name': sub.name,
                'period_ends_at': sub.current_period_ends_at.isoformat(),
            })
        return snapshots

    def _revert_active_subscriptions_on_reopen(self) -> list[dict]:
        """On reopen, flip every Subscription tied to this invoice
        from ACTIVE back to PENDING. Refuses if any of those
        subscriptions have a redemption ledger entry — the same
        rule as packages, for the same reason: orphaning a
        redemption is unsafe."""
        from apps.memberships.models import (
            Subscription,
            SubscriptionRedemption,
        )

        active = list(
            Subscription.objects
            .select_for_update()
            .filter(
                source_invoice_line__invoice=self,
                status=Subscription.Status.ACTIVE,
            )
        )
        if not active:
            return []
        redemption_count = SubscriptionRedemption.objects.filter(
            subscription__in=active,
        ).count()
        if redemption_count > 0:
            raise InvoiceStateError(
                'Cannot reopen this invoice: a membership on it has '
                'already been redeemed against. Reverse the '
                'redemption(s) first.',
            )
        snapshots: list[dict] = []
        for sub in active:
            sub.status = Subscription.Status.PENDING
            sub.started_at = None
            sub.current_period_starts_at = None
            sub.current_period_ends_at = None
            sub.save(update_fields=[
                'status', 'started_at', 'current_period_starts_at',
                'current_period_ends_at', 'updated_at',
            ])
            snapshots.append({
                'subscription_id': sub.pk,
                'name': sub.name,
            })
        return snapshots

    def _cancel_pending_subscriptions(self, *, by_user) -> list[dict]:
        """On invoice void, cascade-cancel any PENDING Subscription
        tied to this invoice (the customer never paid)."""
        from apps.memberships.models import Subscription

        pending = list(
            Subscription.objects
            .select_for_update()
            .filter(
                source_invoice_line__invoice=self,
                status=Subscription.Status.PENDING,
            )
        )
        snapshots: list[dict] = []
        now = timezone.now()
        for sub in pending:
            sub.status = Subscription.Status.CANCELLED
            sub.cancelled_at = now
            sub.cancelled_by = by_user
            sub.cancel_reason = 'invoice_voided'
            sub.save(update_fields=[
                'status', 'cancelled_at', 'cancelled_by',
                'cancel_reason', 'updated_at',
            ])
            snapshots.append({
                'subscription_id': sub.pk,
                'name': sub.name,
            })
        return snapshots

    # ── Gift card lifecycle side effects ─────────────────────────────────

    def _activate_pending_gift_cards(self, *, by_user) -> list[dict]:
        """When the invoice closes, flip every PENDING GiftCard whose
        `source_invoice_line` is on this invoice to ACTIVE, set
        `issued_at = now`, and write the ISSUE ledger row that
        carries the initial balance.

        Returns audit-snapshot dicts. Caller is already inside a
        transaction.
        """
        from apps.giftcards.models import GiftCard, GiftCardLedger

        now = timezone.now()
        pending = (
            GiftCard.objects
            .select_for_update()
            .filter(
                source_invoice_line__invoice=self,
                status=GiftCard.Status.PENDING,
            )
        )
        snapshots: list[dict] = []
        for gc in pending:
            gc.status = GiftCard.Status.ACTIVE
            gc.issued_at = now
            # Card was created with balance_cents=0 in PENDING; the
            # ISSUE row + balance bump happen here, so the invariant
            # `balance == sum(ledger)` holds end-to-end.
            gc.balance_cents = gc.initial_value_cents
            gc.save(update_fields=[
                'status', 'issued_at', 'balance_cents', 'updated_at',
            ])
            GiftCardLedger.objects.create(
                tenant=gc.tenant,
                gift_card=gc,
                kind=GiftCardLedger.Kind.ISSUE,
                amount_cents=gc.initial_value_cents,
                invoice=self,
                by_user=by_user,
                note='Issued on invoice close',
            )
            snapshots.append({
                'gift_card_id': gc.pk,
                'code': gc.code,
                'value_cents': gc.initial_value_cents,
            })
        return snapshots

    def _revert_active_gift_cards_on_reopen(self) -> list[dict]:
        """On reopen, flip every GiftCard tied to this invoice from
        ACTIVE back to PENDING. Refuses if any of those cards have
        had a redemption (would orphan the ledger). Also refuses if
        THIS invoice itself had any gift card credits applied
        (the redemption side) — operator must reverse those first.
        """
        from apps.giftcards.models import GiftCard, GiftCardLedger

        # Refuse if this invoice has any redemption ledger entries
        # against it (this invoice consumed gift card balance).
        consumed_count = GiftCardLedger.objects.filter(
            invoice=self,
            kind=GiftCardLedger.Kind.REDEEM,
        ).count()
        if consumed_count > 0:
            raise InvoiceStateError(
                'Cannot reopen this invoice: it had gift card credits '
                'applied. Reverse the redemption(s) first.',
            )

        # Cards SOLD on this invoice — revert if no redemptions.
        sold = list(
            GiftCard.objects
            .select_for_update()
            .filter(
                source_invoice_line__invoice=self,
                status=GiftCard.Status.ACTIVE,
            )
        )
        if not sold:
            return []

        sold_redeem_count = GiftCardLedger.objects.filter(
            gift_card__in=sold,
            kind=GiftCardLedger.Kind.REDEEM,
        ).count()
        if sold_redeem_count > 0:
            raise InvoiceStateError(
                'Cannot reopen this invoice: a gift card sold on it '
                'has already been redeemed against. Reverse the '
                'redemption(s) first.',
            )

        snapshots: list[dict] = []
        for gc in sold:
            # Delete the ISSUE ledger row tied to this invoice and
            # zero the balance. Reopen → re-close will write a fresh
            # ISSUE row.
            GiftCardLedger.objects.filter(
                gift_card=gc,
                kind=GiftCardLedger.Kind.ISSUE,
                invoice=self,
            ).delete()
            gc.status = GiftCard.Status.PENDING
            gc.issued_at = None
            gc.balance_cents = 0
            gc.save(update_fields=[
                'status', 'issued_at', 'balance_cents', 'updated_at',
            ])
            snapshots.append({'gift_card_id': gc.pk, 'code': gc.code})
        return snapshots

    def _void_pending_gift_cards(self, *, by_user) -> list[dict]:
        """On invoice void, mark any PENDING GiftCard tied to this
        invoice as VOIDED. The customer never paid for them."""
        from apps.giftcards.models import GiftCard

        pending = list(
            GiftCard.objects
            .select_for_update()
            .filter(
                source_invoice_line__invoice=self,
                status=GiftCard.Status.PENDING,
            )
        )
        snapshots: list[dict] = []
        now = timezone.now()
        for gc in pending:
            gc.status = GiftCard.Status.VOIDED
            gc.voided_at = now
            gc.voided_by = by_user
            gc.void_reason = 'invoice_voided'
            gc.save(update_fields=[
                'status', 'voided_at', 'voided_by', 'void_reason', 'updated_at',
            ])
            snapshots.append({'gift_card_id': gc.pk, 'code': gc.code})
        return snapshots

    # ── State transitions ────────────────────────────────────────────────

    def close(self, *, by_user, payment_method: str, payment_reference: str = '', notes: str = ''):
        """Close (take payment) — transitions status OPEN → PAID and
        marks the linked appointment COMPLETED.

        Acquires a row-level lock on the invoice (and on the appointment,
        if any) so concurrent close requests serialize. Raises
        `InvoiceStateError` if the invoice is not OPEN, or
        `InvoiceStateError` if a linked appointment is in a cancelled or
        no-show terminal state (those can't be retroactively completed).

        Caller is responsible for permission checking (`PROCESS_PAYMENT`)
        before invoking; the model layer enforces invariants only.
        """
        # Late import — avoid circular at module load time.
        from apps.appointments.models import Appointment
        from apps.audit.models import AuditLog
        from apps.audit.services import record

        if not payment_method:
            raise InvoiceStateError('payment_method is required to close an invoice.')
        valid_methods = {choice[0] for choice in self.PaymentMethod.choices}
        if payment_method not in valid_methods:
            raise InvoiceStateError(f'Unknown payment_method: {payment_method!r}.')

        with transaction.atomic():
            # Re-read with a row lock to defeat lost-update races. Two
            # concurrent close() calls serialize: the first transitions
            # OPEN→PAID and commits; the second sees PAID and raises.
            locked = (
                Invoice.objects.select_for_update()
                .get(pk=self.pk)
            )
            if locked.status == self.Status.PAID:
                raise InvoiceStateError(
                    'Invoice is already paid. Reopen it first if you need to re-close.',
                )
            if locked.status == self.Status.VOID:
                raise InvoiceStateError('Cannot close a voided invoice.')

            now = timezone.now()
            locked.status = self.Status.PAID
            locked.payment_method = payment_method
            locked.payment_reference = payment_reference
            if notes:
                locked.notes = (locked.notes + '\n' if locked.notes else '') + notes
            # First close sets closed_at; subsequent re-closes do not
            # update it (that's the user's "60 days from FIRST close" rule).
            if locked.closed_at is None:
                locked.closed_at = now
            locked.closed_by = by_user
            locked.save(update_fields=[
                'status', 'payment_method', 'payment_reference', 'notes',
                'closed_at', 'closed_by', 'updated_at',
            ])

            # Coordinate the appointment side, if any. Lock it for the
            # transition; refuse to complete cancelled/no-show appointments.
            appt_id = locked.appointment_id
            if appt_id is not None:
                appt = (
                    Appointment.objects.select_for_update()
                    .get(pk=appt_id)
                )
                if appt.status in (Appointment.Status.CANCELLED, Appointment.Status.NO_SHOW):
                    raise InvoiceStateError(
                        f'Cannot close invoice for a {appt.get_status_display().lower()} appointment.',
                    )
                appt.status = Appointment.Status.COMPLETED
                appt.completed_at = now
                if not appt.checked_in_at:
                    appt.checked_in_at = now
                appt.save(update_fields=[
                    'status', 'completed_at', 'checked_in_at', 'updated_at',
                ])

            # Decrement product stock for every retail line. Idempotent
            # only across separate close→reopen→close cycles via the
            # restock-on-reopen pair (NOT idempotent for double-clicks
            # — the row lock at the top of this method is what defeats
            # those).
            inventory_snapshot = locked._apply_inventory_delta(sign=-1)
            # Flip any PENDING PurchasedPackages to ACTIVE — credits
            # become drawable now that the customer has paid.
            packages_activated = locked._activate_pending_packages()
            # Same flip for memberships: PENDING → ACTIVE + period
            # dates set from the snapshot's billing_interval.
            subscriptions_activated = locked._activate_pending_subscriptions()
            # And gift cards: PENDING → ACTIVE + write the ISSUE
            # ledger row that establishes the initial balance.
            gift_cards_activated = locked._activate_pending_gift_cards(
                by_user=by_user,
            )
            # Accrue commission on each service line whose provider
            # has an active CommissionRule. Idempotent — a line
            # that already has an un-reversed accrual is skipped.
            from apps.commissions.services import accrue_for_invoice
            commissions_accrued = accrue_for_invoice(
                invoice=locked, by_user=by_user,
            )

            record(
                action=AuditLog.Action.UPDATE,
                resource_type='invoice',
                resource_id=locked.pk,
                user=by_user,
                tenant=locked.tenant,
                metadata={
                    'transition': 'open→paid',
                    'total_cents': locked.total_cents,
                    'payment_method': payment_method,
                    'payment_reference': payment_reference,
                    'appointment_id': appt_id,
                    'first_close': locked.reopen_count == 0,
                    'inventory': inventory_snapshot,
                    'packages_activated': packages_activated,
                    'subscriptions_activated': subscriptions_activated,
                    'gift_cards_activated': gift_cards_activated,
                    'commissions_accrued': commissions_accrued,
                },
            )

            # Refresh self so the caller sees the new state.
            self.refresh_from_db()
            return self

    def reopen(self, *, by_user, reason: str = ''):
        """Reopen a paid invoice — transitions PAID → OPEN and reverts
        the linked appointment to CHECKED_IN.

        Permission and time checks:

          - The caller must hold `REOPEN_INVOICE` (owner / manager). The
            view enforces this before invoking; the model rechecks for
            defense in depth.
          - Must be within `REOPEN_WINDOW_DAYS` (60 days) of `closed_at`,
            the FIRST close. Re-closes after a reopen do not extend the
            window (the user's explicit business rule).
        """
        from apps.appointments.models import Appointment
        from apps.audit.models import AuditLog
        from apps.audit.services import record

        with transaction.atomic():
            locked = (
                Invoice.objects.select_for_update()
                .get(pk=self.pk)
            )
            if locked.status != self.Status.PAID:
                raise InvoiceStateError(
                    f'Only paid invoices can be reopened (current status: {locked.get_status_display()}).',
                )
            if not locked.is_reopen_window_open:
                raise InvoiceReopenWindowError(
                    f'Reopen window has expired (was open until '
                    f'{locked.reopen_deadline.isoformat()}).',
                )

            now = timezone.now()
            days_since_first_close = (now - locked.closed_at).days
            locked.status = self.Status.OPEN
            locked.reopened_at = now
            locked.reopened_by = by_user
            locked.reopen_count = locked.reopen_count + 1
            locked.save(update_fields=[
                'status', 'reopened_at', 'reopened_by', 'reopen_count', 'updated_at',
            ])

            appt_id = locked.appointment_id
            if appt_id is not None:
                appt = (
                    Appointment.objects.select_for_update()
                    .get(pk=appt_id)
                )
                # Always revert to CHECKED_IN; the service was delivered
                # (we don't try to restore the pre-close status — that's
                # virtually always CHECKED_IN anyway and the reverse
                # mapping isn't worth the complexity).
                appt.status = Appointment.Status.CHECKED_IN
                appt.completed_at = None
                appt.save(update_fields=['status', 'completed_at', 'updated_at'])

            # Revert ACTIVE PurchasedPackages back to PENDING. Refuses
            # if any of them have been redeemed against — the
            # operator must reverse the redemptions first.
            packages_reverted = locked._revert_active_packages_on_reopen()
            # Same revert for memberships, with the same redemption-
            # ledger guard.
            subscriptions_reverted = (
                locked._revert_active_subscriptions_on_reopen()
            )
            # And gift cards: revert ACTIVE → PENDING for cards SOLD
            # on this invoice (refuses if redeemed against), and
            # refuses if THIS invoice consumed gift card balance.
            gift_cards_reverted = locked._revert_active_gift_cards_on_reopen()
            # Restock — reverse the close-time decrement so on-hand
            # counts go back to where they were before the sale.
            inventory_snapshot = locked._apply_inventory_delta(sign=+1)
            # Reverse every un-reversed commission accrual against
            # this invoice. If the invoice closes again, fresh
            # accruals get written on top.
            from apps.commissions.services import reverse_for_invoice
            commissions_reversed = reverse_for_invoice(
                invoice=locked, by_user=by_user,
            )

            record(
                action=AuditLog.Action.UPDATE,
                resource_type='invoice',
                resource_id=locked.pk,
                user=by_user,
                tenant=locked.tenant,
                metadata={
                    'transition': 'paid→open',
                    'reopen_count': locked.reopen_count,
                    'days_since_first_close': days_since_first_close,
                    'reason': reason,
                    'appointment_id': appt_id,
                    'inventory': inventory_snapshot,
                    'packages_reverted': packages_reverted,
                    'subscriptions_reverted': subscriptions_reverted,
                    'gift_cards_reverted': gift_cards_reverted,
                    'commissions_reversed': commissions_reversed,
                },
            )

            self.refresh_from_db()
            return self

    def void(self, *, by_user, reason: str):
        """Void an open invoice — terminal. Use for comp'd visits,
        booking errors, etc.

        Voiding a PAID invoice is not permitted (would lose the payment
        record). To reverse a paid invoice, reopen it first then void.
        Reopen is itself time-bounded, which is intentional — the system
        does not permit silently erasing an old paid invoice.
        """
        from apps.audit.models import AuditLog
        from apps.audit.services import record

        if not reason:
            raise InvoiceStateError('A reason is required to void an invoice.')

        with transaction.atomic():
            locked = (
                Invoice.objects.select_for_update()
                .get(pk=self.pk)
            )
            if locked.status == self.Status.VOID:
                raise InvoiceStateError('Invoice is already voided.')
            if locked.status == self.Status.PAID:
                raise InvoiceStateError(
                    'Cannot void a paid invoice directly. Reopen it first '
                    '(within the 60-day window, requires manager/owner).',
                )

            now = timezone.now()
            locked.status = self.Status.VOID
            locked.voided_at = now
            locked.voided_by = by_user
            locked.void_reason = reason
            locked.save(update_fields=[
                'status', 'voided_at', 'voided_by', 'void_reason', 'updated_at',
            ])

            # Cascade-void any PENDING PurchasedPackages on this
            # invoice — the customer never paid, so the credits
            # never become real.
            packages_voided = locked._void_pending_packages()
            # Same cascade-cancel for PENDING Subscriptions on this
            # invoice.
            subscriptions_cancelled = (
                locked._cancel_pending_subscriptions(by_user=by_user)
            )
            # And gift cards: cascade-VOIDED for any PENDING cards.
            gift_cards_voided = locked._void_pending_gift_cards(
                by_user=by_user,
            )

            record(
                action=AuditLog.Action.UPDATE,
                resource_type='invoice',
                resource_id=locked.pk,
                user=by_user,
                tenant=locked.tenant,
                metadata={
                    'transition': 'open→void',
                    'reason': reason,
                    'appointment_id': locked.appointment_id,
                    'packages_voided': packages_voided,
                    'subscriptions_cancelled': subscriptions_cancelled,
                    'gift_cards_voided': gift_cards_voided,
                },
            )

            self.refresh_from_db()
            return self


# ── Line items ───────────────────────────────────────────────────────────


class InvoiceLineItem(models.Model):
    """A single billable line on an invoice.

    Snapshots `description`, `unit_price_cents`, and `tax_rate_percent`
    at line-creation time. Subsequent changes to the source `Service`
    do not alter historical lines — that's a hard requirement for
    financial reporting integrity (SOC 2 PI1.1) and matches what every
    POS system in the industry does.

    The line totals (`line_subtotal_cents`, `line_tax_cents`) are
    recomputed in `save()` from `quantity * unit_price_cents` and the
    snapshot tax rate. A DB CheckConstraint enforces
    `line_subtotal_cents = quantity * unit_price_cents`.
    """

    invoice = models.ForeignKey(
        Invoice,
        on_delete=models.CASCADE,
        related_name='line_items',
    )
    service = models.ForeignKey(
        'services.Service',
        on_delete=models.PROTECT,
        related_name='+',
        null=True,
        blank=True,
        help_text='Source service. Null for retail / ad-hoc lines.',
    )
    product = models.ForeignKey(
        'products.Product',
        on_delete=models.PROTECT,
        related_name='+',
        null=True,
        blank=True,
        help_text=(
            'Source retail product. Null for service / package / ad-hoc lines. '
            'Mutually exclusive with `service` and `package`.'
        ),
    )
    package = models.ForeignKey(
        'packages.Package',
        on_delete=models.PROTECT,
        related_name='+',
        null=True,
        blank=True,
        help_text=(
            'Source catalog package. Null for service / product / membership / '
            'ad-hoc lines. When set, a `PurchasedPackage` row is created tied '
            '1:1 to this line and flipped ACTIVE when the invoice closes.'
        ),
    )
    membership_plan = models.ForeignKey(
        'memberships.MembershipPlan',
        on_delete=models.PROTECT,
        related_name='+',
        null=True,
        blank=True,
        help_text=(
            'Source membership plan. Null for service / product / package / '
            'ad-hoc lines. When set, a `Subscription` row is created tied '
            '1:1 to this line and flipped ACTIVE when the invoice closes.'
        ),
    )
    description = models.CharField(
        max_length=200,
        help_text='Snapshot of the service name (or arbitrary description for non-service items).',
    )
    quantity = models.PositiveIntegerField(default=1)
    unit_price_cents = models.PositiveIntegerField()
    tax_rate_percent = models.DecimalField(
        max_digits=6,
        decimal_places=3,
        default=0,
        help_text='Snapshot of the service tax rate at line creation.',
    )
    line_subtotal_cents = models.PositiveIntegerField(default=0)
    line_tax_cents = models.PositiveIntegerField(default=0)

    # Per-line discount. Same kind / input / cents shape as the
    # invoice-level discount above — see `Invoice.invoice_discount_*`
    # for the rationale. Per-line discount is the operator's "$5 off
    # this Botox / 20% off this peel" lever; invoice-level layers on
    # top of any per-line discounts and is distributed pro-rata.

    class LineDiscountKind(models.TextChoices):
        AMOUNT = 'amount', 'Amount off ($)'
        PERCENT = 'percent', 'Percent off (%)'

    discount_kind = models.CharField(
        max_length=10,
        choices=LineDiscountKind.choices,
        default=LineDiscountKind.AMOUNT,
    )
    discount_input = models.DecimalField(
        max_digits=8, decimal_places=2, default=0,
        help_text=(
            "Operator-typed value. For 'amount' kind: dollars off "
            "this line. For 'percent' kind: percent off this line."
        ),
    )
    discount_cents = models.PositiveIntegerField(
        default=0,
        help_text=(
            "Derived cents off this line. Computed in `save()` from "
            "kind + input, capped at `line_subtotal_cents`."
        ),
    )
    discount_reason = models.CharField(
        max_length=200, blank=True, default='',
    )
    # The per-line absorption of the invoice-level discount, computed
    # by `Invoice.recalculate_totals` pro-rata on the after-line-
    # discount basis. Not directly mutable by callers.
    invoice_discount_share_cents = models.PositiveIntegerField(default=0)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['id']
        constraints = [
            models.CheckConstraint(
                condition=models.Q(quantity__gt=0),
                name='invoice_lines_quantity_positive',
            ),
            models.CheckConstraint(
                condition=models.Q(line_subtotal_cents=models.F('quantity') * models.F('unit_price_cents')),
                name='invoice_lines_subtotal_matches_qty_times_price',
            ),
            # A line is at-most-one-of (service, product, package,
            # membership_plan). All-null allowed for ad-hoc fees /
            # manual lines. Pairwise mutual exclusion is enough — if
            # every pair has ≤1 non-null, the set does too.
            models.CheckConstraint(
                condition=(
                    (models.Q(service__isnull=True) | models.Q(product__isnull=True))
                    & (models.Q(service__isnull=True) | models.Q(package__isnull=True))
                    & (models.Q(service__isnull=True) | models.Q(membership_plan__isnull=True))
                    & (models.Q(product__isnull=True) | models.Q(package__isnull=True))
                    & (models.Q(product__isnull=True) | models.Q(membership_plan__isnull=True))
                    & (models.Q(package__isnull=True) | models.Q(membership_plan__isnull=True))
                ),
                name='invoice_lines_at_most_one_source',
            ),
        ]

    def __str__(self):
        return f'{self.description} × {self.quantity}'

    def save(self, *args, **kwargs):
        # Recompute denormalized totals from the source-of-truth fields.
        self.line_subtotal_cents = self.quantity * self.unit_price_cents
        # Per-line discount derives from kind + input, capped at the
        # line's pre-discount subtotal so we never go negative. The
        # invoice's share of the invoice-level discount is NOT applied
        # here — `Invoice.recalculate_totals` overwrites
        # `invoice_discount_share_cents` + `line_tax_cents` after this
        # save returns. The intermediate tax we compute here is just a
        # sane initial value in case the recalc is skipped (which it
        # isn't in normal flow).
        self.discount_cents = self._compute_line_discount_cents()
        post_discount = max(0, self.line_subtotal_cents - self.discount_cents)
        self.line_tax_cents = compute_line_tax_cents(
            post_discount, self.tax_rate_percent,
        )
        super().save(*args, **kwargs)
        # Roll the change up to the invoice header so totals stay
        # consistent. `recalculate_totals` will redistribute the
        # invoice-level discount + recompute each line's tax on the
        # final post-discount basis via QuerySet.update() (bypassing
        # save() to avoid re-entering this method).
        self.invoice.recalculate_totals()

    def _compute_line_discount_cents(self) -> int:
        """Translate the operator-typed (kind, input) into cents. Caps
        at `line_subtotal_cents` so a 200% discount or a $999 amount
        on a $50 line both come out as the full $50 off — never
        below zero. The cap matches what spas expect (no negative
        line items)."""
        if self.discount_input is None or self.discount_input <= 0:
            return 0
        if self.discount_kind == self.LineDiscountKind.PERCENT:
            # Decimal math to avoid float drift on common values
            # (10% of $33.33 etc.). Round half-up.
            from decimal import ROUND_HALF_UP, Decimal
            pct = Decimal(self.discount_input)
            cents = int(
                (Decimal(self.line_subtotal_cents) * pct / Decimal(100))
                .quantize(Decimal('1'), rounding=ROUND_HALF_UP),
            )
        else:
            # 'amount' kind — input is dollars, multiply by 100 → cents.
            from decimal import Decimal
            cents = int(Decimal(self.discount_input) * 100)
        return min(max(0, cents), self.line_subtotal_cents)


# ── Domain exceptions ────────────────────────────────────────────────────


class InvoiceStateError(Exception):
    """Raised when an invoice state transition is invalid (wrong source
    state, missing required field, terminal state, etc.). Caught at the
    view layer and surfaced as 400/409."""


class InvoiceReopenWindowError(InvoiceStateError):
    """Raised when reopen is attempted past the 60-day window. Subclass of
    `InvoiceStateError` so generic handlers catch both, but specific
    handlers can distinguish the time-bounded case to surface a clearer
    message ("the 60-day window has passed")."""
