# Generated by Django 5.1.15 on 2026-05-15 21:26

import apps.portal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_email_marketing_consent_at_and_more'),
        ('tenants', '0012_tenant_confirmation_sms_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.portal.models._generate_portal_token, help_text='Random session token. Stored in the browser cookie verbatim.', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Set when the customer logs out (or staff revokes). Once set, the session is dead.', null=True)),
                ('issued_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', help_text='User-Agent of the client that consumed the magic link. For audit display; not used for any enforcement.', max_length=300)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'customer', '-last_seen_at'], name='portal_cust_tenant__bee05b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerPortalToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=apps.portal.models._generate_portal_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp the token was consumed. Single-use; non-null = spent.', null=True)),
                ('requested_ip', models.GenericIPAddressField(blank=True, help_text='IP address that asked for the magic link, for the audit trail. Not used for any enforcement decision — IPs are too easy to spoof / share / change to be load-bearing.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(help_text="The customer the magic link will authenticate as. CASCADE so deleting a customer invalidates any outstanding tokens for them — we don't want a dangling token granting access to a removed account.", on_delete=django.db.models.deletion.CASCADE, related_name='portal_tokens', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['tenant', 'customer', '-created_at'], name='portal_cust_tenant__2adf1e_idx')],
            },
        ),
    ]
