# Generated by Django 5.1.15 on 2026-05-04 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0008_providerschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('meta_facebook', 'Facebook Page Messenger'), ('meta_instagram', 'Instagram Business DMs'), ('meta_whatsapp', 'WhatsApp Business')], max_length=32)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('error', 'Error')], db_index=True, default='disconnected', max_length=16)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('external_name', models.CharField(blank=True, default='', max_length=256)),
                ('auth_data', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_message', models.CharField(blank=True, default='', max_length=500)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['provider'],
                'indexes': [models.Index(fields=['tenant', 'provider'], name='integration_tenant__8866da_idx'), models.Index(fields=['tenant', 'status'], name='integration_tenant__5f860b_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'provider'), name='integrations_one_connection_per_tenant_provider')],
            },
        ),
    ]
