# Generated by Django 5.1.15 on 2026-05-16 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_acquisition_and_instagram'),
        ('integrations', '0002_encrypt_auth_data'),
        ('tenants', '0012_tenant_confirmation_sms_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook Messenger'), ('whatsapp', 'WhatsApp')], db_index=True, max_length=16)),
                ('external_thread_id', models.CharField(help_text='Provider-scoped sender ID (Meta PSID, etc.)', max_length=128)),
                ('external_username', models.CharField(blank=True, default='', help_text='Human-readable @handle if known.', max_length=128)),
                ('last_message_at', models.DateTimeField(db_index=True)),
                ('last_inbound_at', models.DateTimeField(blank=True, help_text="When the customer last sent us a message. Used to enforce Meta's 24-hour reply window in Session 2.", null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text="When an operator last marked this thread read. Null means unread; we don't track per-message read state on the operator side, only thread-level.", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(help_text="The connected account this thread belongs to. PROTECT because deleting a connection shouldn't erase message history — disconnect leaves the thread + messages intact.", on_delete=django.db.models.deletion.PROTECT, related_name='social_threads', to='integrations.connection')),
                ('customer', models.ForeignKey(help_text='The person on the other side. May be a social-guest row (`is_social_guest=True`) if the operator has not yet merged this conversation into an existing client record.', on_delete=django.db.models.deletion.PROTECT, related_name='social_threads', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound (staff → customer)'), ('inbound', 'Inbound (customer → staff)')], db_index=True, max_length=16)),
                ('body', models.TextField(blank=True, default='', help_text='Text content of the message. May be empty when the message is media-only (image / video / sticker).')),
                ('media_urls', models.TextField(blank=True, default='', help_text='Newline-separated provider-hosted URLs for media attachments. These expire (Meta retains for ~24h); a future polish will copy to our S3 + sign.')),
                ('external_message_id', models.CharField(help_text="Provider's per-message ID (Meta `mid`). Used for idempotency.", max_length=128)),
                ('status', models.CharField(choices=[('received', 'Received'), ('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read by recipient'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('received_at', models.DateTimeField(blank=True, help_text='When the provider reports the message was created on their side.', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Provider-reported read receipt (NOT operator-marked read).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_by', models.ForeignKey(blank=True, help_text='Staff user who composed the message. Outbound only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='integrations.socialthread')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='socialthread',
            index=models.Index(fields=['tenant', '-last_message_at'], name='social_thread_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='socialthread',
            index=models.Index(fields=['tenant', 'customer', '-last_message_at'], name='social_thread_per_customer_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialthread',
            constraint=models.UniqueConstraint(fields=('tenant', 'provider', 'external_thread_id'), name='social_thread_unique_per_tenant_provider_sender'),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['tenant', 'thread', 'created_at'], name='social_msg_thread_chrono_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmessage',
            index=models.Index(fields=['tenant', 'external_message_id'], name='social_msg_external_id_idx'),
        ),
        migrations.AddConstraint(
            model_name='socialmessage',
            constraint=models.UniqueConstraint(fields=('tenant', 'external_message_id'), name='social_message_unique_external_id'),
        ),
    ]
