# Generated by Django 5.1.15 on 2026-05-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_social_messaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(db_index=True, max_length=64, unique=True)),
                ('external_user_id', models.CharField(db_index=True, max_length=128)),
                ('affected_page_ids', models.JSONField(blank=True, default=list)),
                ('affected_connection_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.CharField(blank=True, default='', max_length=500)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['external_user_id', '-requested_at'], name='integration_externa_0415cf_idx')],
            },
        ),
    ]
