# Generated by Django 5.1.15 on 2026-05-17 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_data_deletion_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmessage',
            name='archived_media_keys',
            field=models.TextField(blank=True, default='', help_text="Newline-separated S3 keys for media we copied off Meta before it expired. `_serialise_message` prefers these + returns short-lived signed URLs so PHI media survives past Meta's 24h retention window. ADR 0027 §6."),
        ),
        migrations.AlterField(
            model_name='socialmessage',
            name='media_urls',
            field=models.TextField(blank=True, default='', help_text='Newline-separated provider-hosted URLs for media attachments. Meta retains these for ~24h then 404s; we copy to our S3 at ingest time and prefer `archived_media_keys` below for long-term display. Original URLs kept for audit / debugging.'),
        ),
    ]
