# Generated by Django 5.1.15 on 2026-05-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_social_message_archived_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmessage',
            name='external_message_id',
            field=models.CharField(help_text="Provider's per-message ID (Meta `mid`). Used for idempotency. Meta IG mids run long (~100-200 chars base64-ish); 255 leaves headroom. 128 was too short and broke ingestion in prod 2026-05-17.", max_length=255),
        ),
        migrations.AlterField(
            model_name='socialthread',
            name='external_thread_id',
            field=models.CharField(help_text='Provider-scoped sender ID. Meta IG conversation IDs run long (~100 chars base64-ish); we use 255 to leave headroom for the longer-than-documented values Meta returns in practice.', max_length=255),
        ),
    ]
