# Generated by Django 5.1.15 on 2026-05-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_widen_external_id_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialthread',
            name='external_display_name',
            field=models.CharField(blank=True, default='', help_text='Instagram display name (their real name as it appears in the IG app). Fetched from Meta\'s Graph API on thread create so the inbox shows "Maria Lopez" rather than the opaque PSID.', max_length=200),
        ),
        migrations.AddField(
            model_name='socialthread',
            name='external_profile_fetched_at',
            field=models.DateTimeField(blank=True, help_text="When the Graph API profile fetch last succeeded. Used to decide whether to re-fetch on next inbound (stale > 6 days to balance freshness vs. API call count against Meta's 200 calls/hour/account ceiling).", null=True),
        ),
        migrations.AddField(
            model_name='socialthread',
            name='external_profile_pic_url',
            field=models.URLField(blank=True, default='', help_text='Meta-hosted CDN URL for the IG profile photo. SIGNED and EPHEMERAL — Meta rotates the signing keys every ~few weeks, after which the URL 403s. Refreshed on every new inbound message so it stays fresh as long as the conversation is active; stale URLs gracefully fall back to initials on the frontend.', max_length=2048),
        ),
    ]
