# Generated by Django 5.1.15 on 2026-04-30 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6b7280', help_text='Hex color for the chip in the UI, e.g. #6b7280', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('emergency_name', models.CharField(blank=True, max_length=200)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_relationship', models.CharField(blank=True, max_length=50)),
                ('medical_history', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('skin_type_fitzpatrick', models.IntegerField(blank=True, help_text='Fitzpatrick skin type 1–6 (relevant for laser treatments).', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('notes', models.TextField(blank=True, help_text='General notes — visible to all staff with client access.')),
                ('referral_source', models.CharField(blank=True, max_length=100)),
                ('email_opt_in', models.BooleanField(default=True)),
                ('sms_opt_in', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('external_source', models.CharField(blank=True, help_text="e.g. 'zenoti', 'vagaro'", max_length=50)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('tags', models.ManyToManyField(blank=True, related_name='customers', to='customers.customertag')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'last_name', 'first_name'], name='customers_c_tenant__42b375_idx'), models.Index(fields=['tenant', 'email'], name='customers_c_tenant__0aea56_idx'), models.Index(fields=['tenant', 'phone'], name='customers_c_tenant__6d2a04_idx'), models.Index(fields=['tenant', 'status'], name='customers_c_tenant__d5e64f_idx'), models.Index(fields=['tenant', 'external_id'], name='customers_c_tenant__b0dc56_idx'), models.Index(fields=['tenant', '-created_at'], name='customers_c_tenant__654515_idx')],
            },
        ),
    ]
