# Generated by Django 5.1.15 on 2026-04-30 — referral code rollout.
#
# Three-step migration:
#   1. Add `referral_code` column (allowed empty so existing rows pass).
#   2. Backfill every existing customer with a unique code per tenant.
#   3. Apply the partial unique constraint.
#
# Step 2 uses `secrets.choice` against the same alphabet as the runtime helper
# so codes are visually consistent. Per-tenant uniqueness is checked against
# the historical model.

import secrets

from django.db import migrations, models


REFERRAL_CODE_ALPHABET = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'
REFERRAL_CODE_LENGTH = 8


def backfill_referral_codes(apps, schema_editor):
    Customer = apps.get_model('customers', 'Customer')

    seen_per_tenant: dict[int, set[str]] = {}
    for code, tenant_id in Customer.objects.exclude(referral_code='').values_list(
        'referral_code', 'tenant_id',
    ):
        seen_per_tenant.setdefault(tenant_id, set()).add(code)

    for customer in Customer.objects.filter(referral_code=''):
        seen = seen_per_tenant.setdefault(customer.tenant_id, set())
        for _ in range(50):
            code = ''.join(
                secrets.choice(REFERRAL_CODE_ALPHABET) for _ in range(REFERRAL_CODE_LENGTH)
            )
            if code not in seen:
                customer.referral_code = code
                customer.save(update_fields=['referral_code'])
                seen.add(code)
                break
        else:
            raise RuntimeError(
                f'Could not generate a unique referral code for customer {customer.pk}'
                f' (tenant {customer.tenant_id}) after 50 attempts.',
            )


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referral_code',
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text='Auto-generated; immutable from the API. Unique within the tenant.',
                max_length=12,
            ),
        ),
        migrations.RunPython(backfill_referral_codes, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(
                condition=models.Q(('referral_code', ''), _negated=True),
                fields=('tenant', 'referral_code'),
                name='customers_unique_tenant_referral_code',
            ),
        ),
    ]
