# Generated by Django 5.1.15 on 2026-05-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_add_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email_marketing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_marketing_consent_source',
            field=models.CharField(blank=True, default='', help_text="e.g. 'booking_form', 'manual_entry', 'import'", max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_marketing_opt_in',
            field=models.BooleanField(default=False, help_text='Explicit consent for promotional / marketing emails. Default False per CAN-SPAM. Flip True only with a deliberate customer act.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_marketing_suppressed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='email_marketing_suppression_source',
            field=models.CharField(blank=True, default='', help_text="e.g. 'unsubscribe_link', 'reply_stop', 'manual', 'bounce', 'complaint'", max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_marketing_consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_marketing_consent_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_marketing_opt_in',
            field=models.BooleanField(default=False, help_text='Explicit consent for promotional / marketing SMS. Default False per TCPA. Flip True only with a deliberate customer act.'),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_marketing_suppressed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='sms_marketing_suppression_source',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
