# Generated by Django 5.1.15 on 2026-05-20 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_acquisition_and_instagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='The existing client whose referral code this client used at intake.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_customers', to='customers.customer'),
        ),
    ]
