# Generated by Django 5.1.15 on 2026-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo_url',
            field=models.URLField(blank=True, help_text="Public URL of the spa's logo. Applied to the login page and public booking page only. Direct upload UI is on the roadmap; for now paste a URL pointing at a hosted PNG/SVG."),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='primary_color',
            field=models.CharField(default='#1f2937', help_text='Brand color as hex (e.g. #1f2937). Applied to the login page and public booking page only.', max_length=7),
        ),
    ]
