# Generated by Django 5.1.15 on 2026-05-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_logo_url_alter_tenant_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='business_close_time',
            field=models.TimeField(default='20:00', help_text='When the spa closes. Reflected on the calendar day view (the time axis ends here) and on the public booking page (no slots that would extend past this time).'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_open_time',
            field=models.TimeField(default='08:00', help_text='When the spa opens. Reflected on the calendar day view (the time axis starts here) and on the public booking page (no slots before this time).'),
        ),
    ]
