# Generated by Django 5.1.15 on 2026-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_business_close_time_tenant_business_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmembership',
            name='employment_notes',
            field=models.TextField(blank=True, help_text='Internal notes about this employment relationship — visible to owners + managers only.'),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contractor', 'Contractor')], help_text='Full-time / part-time / contractor at this tenant.', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='pay_rate_cents',
            field=models.PositiveIntegerField(default=0, help_text='Pay rate in cents. Interpretation depends on pay_type: cents/hour for HOURLY, cents/year for SALARY, ignored for COMMISSION_ONLY. Stored as an integer to dodge float rounding on the money path.'),
        ),
        migrations.AddField(
            model_name='tenantmembership',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('salary', 'Salary'), ('commission_only', 'Commission only')], help_text='How this person is paid. Commission-only means no base pay.', max_length=20),
        ),
    ]
