# Generated by Django 5.1.15 on 2026-05-02 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenantmembership_employment_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. "Manhattan" or "Brooklyn".', max_length=120)),
                ('slug', models.SlugField(help_text='URL-safe identifier scoped to the tenant (used by the active-location cookie).', max_length=63)),
                ('is_default', models.BooleanField(default=False, help_text='Exactly one location per tenant is the default. Used as the fallback when no active location is set (fresh login, missing cookie, deleted location). Enforced by a partial unique index on (tenant, is_default=True).')),
                ('is_active', models.BooleanField(default=True)),
                ('timezone', models.CharField(default='America/New_York', help_text='IANA timezone for this site. Different sites of the same business may differ.', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Site-specific contact email; falls back to tenant email if blank.', max_length=254)),
                ('address_line1', models.CharField(blank=True, max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('business_open_time', models.TimeField(default='08:00', help_text="When this site opens. Drives this location's calendar day-axis bounds.")),
                ('business_close_time', models.TimeField(default='20:00', help_text="When this site closes. Drives this location's calendar day-axis bounds.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='tenants.tenant')),
            ],
            options={
                'ordering': ['tenant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_assignments', to='tenants.location')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_assignments', to='tenants.tenantmembership')),
            ],
            options={
                'ordering': ['location', 'membership'],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='unique_location_slug_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('tenant',), name='one_default_location_per_tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='membershiplocation',
            unique_together={('membership', 'location')},
        ),
    ]
