# Generated by Django 5.1.15 on 2026-05-02 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_drop_per_location_fields_from_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_hours', models.JSONField(default=dict, help_text='Per-weekday blocks: {"monday": [{"start": "09:00", "end": "17:00"}], ...}. Empty array per day = off. Multiple blocks per day support split shifts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('membership_location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='tenants.membershiplocation')),
            ],
            options={
                'ordering': ['membership_location'],
            },
        ),
    ]
