# Generated by Django 5.1.15 on 2026-05-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0008_providerschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='online_booking_cancellation_policy',
            field=models.TextField(blank=True, default='', help_text='Cancellation / no-show policy text shown to customers on the booking detail page and the manage-booking page. Plain text; no formatting. Most spas paste their existing "24-hour notice required" language here.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='online_booking_enabled',
            field=models.BooleanField(default=True, help_text='Master switch for the public booking page. When off, the booking URL returns 404.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='online_booking_lead_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Minimum minutes before a slot can be booked online. Front desk uses this to guarantee prep time. 30 min is a reasonable default; busy med-spas often raise this to 120.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='online_booking_welcome_message',
            field=models.TextField(blank=True, default='', help_text='Optional greeting shown above the service catalog on the public booking page. Two or three sentences max — used for seasonal promos, "new patient welcome" copy, or parking / accessibility notes.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='online_booking_window_days',
            field=models.PositiveIntegerField(default=60, help_text='How many days into the future customers can book. Caps speculative bookings far out (which are also the most likely to no-show). Set to a small number during peak season; large during slow seasons.'),
        ),
    ]
