# Generated by Django 5.1.15 on 2026-05-12 19:16

import apps.tenants.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Recipient address. Case-insensitive uniqueness within a tenant for pending (unaccepted, unexpired) invitations is enforced by service-layer check before insert — partial-unique-index in DB is hard to express across `accepted_at IS NULL AND expires_at > now()`.', max_length=254)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('front_desk', 'Front Desk'), ('provider', 'Provider'), ('bookkeeper', 'Bookkeeper'), ('marketing', 'Marketing')], max_length=20)),
                ('is_bookable', models.BooleanField(default=False)),
                ('token', models.CharField(default=apps.tenants.models._generate_invitation_token, editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(default=apps.tenants.models._default_invitation_expiry)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_accepted', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
                ('job_title', models.ForeignKey(blank=True, help_text='Optional job-title assignment to apply on accept.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tenants.jobtitle')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'email'], name='tenants_inv_tenant__9854b9_idx'), models.Index(fields=['tenant', 'accepted_at'], name='tenants_inv_tenant__056543_idx')],
            },
        ),
    ]
