# Generated by Django 5.1.15 on 2026-05-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0010_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='twilio_from_number',
            field=models.CharField(blank=True, default='', help_text='Per-tenant SMS sender (E.164, e.g. "+18885551234"). When blank, falls back to the platform-default TWILIO_FROM_NUMBER. Recipients see this number as the From; reputation lives on this number per tenant.', max_length=20),
        ),
    ]
