# Generated by Django 5.1.15 on 2026-05-15 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_tenant_twilio_from_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='confirmation_sms_template',
            field=models.TextField(blank=True, default='', help_text='Custom SMS body sent when an appointment is booked. Empty falls back to the platform default. Tokens: {{first_name}}, {{spa_name}}, {{appointment_time}}.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='google_review_url',
            field=models.URLField(blank=True, default='', help_text="The tenant's Google Place review URL (e.g. https://g.page/r/CXXXXX/review). Substituted into the {{review_url}} token. When blank + the template references the token, the worker skips the send rather than text a broken link.", max_length=500),
        ),
        migrations.AddField(
            model_name='tenant',
            name='reminder_sms_template',
            field=models.TextField(blank=True, default='', help_text='Custom SMS body sent 24 hours before the appointment. Empty falls back to the platform default. Tokens: {{first_name}}, {{spa_name}}, {{appointment_time}}.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='review_request_enabled',
            field=models.BooleanField(default=False, help_text="Explicit opt-in for the post-appointment review-request SMS. Defaults False so tenants don't accidentally send reviews requests before they've set their Google Review URL. The cron worker skips this tenant when False."),
        ),
        migrations.AddField(
            model_name='tenant',
            name='review_request_hours_after',
            field=models.PositiveSmallIntegerField(default=24, help_text='How many hours after appointment completion the review request should go out. 24 (next day) is the industry default — gives the customer time to enjoy the result + still keeps the experience fresh in their mind.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='review_request_sms_template',
            field=models.TextField(blank=True, default='', help_text='Custom SMS body sent after an appointment is marked completed (waits `review_request_hours_after` hours). Empty falls back to the platform default. Tokens: {{first_name}}, {{spa_name}}, {{review_url}}.'),
        ),
    ]
