# Generated by Django 5.1.15 on 2026-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_tenant_confirmation_sms_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='addon_quantities',
            field=models.JSONField(blank=True, default=dict, help_text='Per-tenant add-on counts: {"staff": 3, "location": 1, "email_5k": 2}. Mirrors Stripe SubscriptionItem quantities.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='baa_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the owner accepted the Business Associate Agreement during self-serve signup.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='baa_version',
            field=models.CharField(blank=True, default='', help_text='Version identifier (e.g. "2026-05") of the BAA accepted. Bumped when BAA text changes; old acceptances stay valid for the version they signed.', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', help_text='Stripe subscription billing cadence.', max_length=10),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_email',
            field=models.EmailField(blank=True, default='', help_text='Where Stripe sends receipts + dunning. Often differs from the owner email.', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_period_email_count',
            field=models.PositiveIntegerField(default=0, help_text='Outbound emails sent in the current billing period. Reset on period roll.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_period_end',
            field=models.DateTimeField(blank=True, help_text='Mirrored from Stripe subscription. End of the current paid period — used to reset monthly usage counters.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='current_period_sms_count',
            field=models.PositiveIntegerField(default=0, help_text='Outbound SMS sent in the current billing period. Reset on period roll.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='grandfathered',
            field=models.BooleanField(default=False, help_text="Set True for the original launch spas onboarded before self-serve pricing existed. Grandfathered tenants are exempt from plan capacity gates, never get the upgrade banner, and aren't enrolled in Stripe Billing. Plan stays PRO for them as a feature-flag convenience."),
        ),
        migrations.AddField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('trial', 'Trial'), ('starter', 'Starter'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='trial', help_text='Active subscription tier. Drives feature gating + capacity caps.', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Customer ID for SaaS subscription billing. Empty for grandfathered tenants who never went through Stripe.', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, default='', help_text='Stripe Subscription ID. Empty for grandfathered tenants.', max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tos_accepted_at',
            field=models.DateTimeField(blank=True, help_text='When the owner accepted the Terms of Service during self-serve signup.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='tos_version',
            field=models.CharField(blank=True, default='', help_text='Version identifier of the ToS accepted.', max_length=32),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the 14-day trial expires. Null for tenants that never went through trial (grandfathered + sales-onboarded Enterprise).', null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past due'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='trial', max_length=20),
        ),
    ]
