# Generated by Django 5.1.15 on 2026-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_grandfather_existing_tenants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the 30-day trial expires. Null for tenants that never went through trial (grandfathered + sales-onboarded Enterprise).', null=True),
        ),
    ]
