# Generated by Django 5.1.15 on 2026-05-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_alter_tenant_trial_ends_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='notifications_sent',
            field=models.JSONField(blank=True, default=dict, help_text='{notification_kind: iso_sent_at}. Used by trial-reminder + dunning crons for idempotency.'),
        ),
    ]
