# Generated by Django 5.1.15 on 2026-05-02 12:29

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('customers', '0002_add_referral_code'),
        ('services', '0003_add_code_tax_type'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='open', max_length=10)),
                ('subtotal_cents', models.PositiveIntegerField(default=0)),
                ('tax_cents', models.PositiveIntegerField(default=0)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('card_external', 'Card (external terminal)'), ('other', 'Other')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, help_text='Free-form: cash drawer #, check #, last 4 of card, etc. Real card-processor transaction IDs land in Phase 2A.', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Internal staff notes.')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_count', models.PositiveIntegerField(default=0)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(blank=True, help_text='The appointment this invoice bills. Null for standalone invoices (POS, packages, gift cards). One-to-one because "all appointments are an invoice" per ADR 0007.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='appointments.appointment')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_closed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='customers.customer')),
                ('reopened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_reopened', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Snapshot of the service name (or arbitrary description for non-service items).', max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price_cents', models.PositiveIntegerField()),
                ('tax_rate_percent', models.DecimalField(decimal_places=3, default=0, help_text='Snapshot of the service tax rate at line creation.', max_digits=6)),
                ('line_subtotal_cents', models.PositiveIntegerField(default=0)),
                ('line_tax_cents', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
                ('service', models.ForeignKey(blank=True, help_text='Source service. Null for non-service items (retail, fees) in future.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'customer', '-created_at'], name='invoices_in_tenant__a1831d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='invoices_in_tenant__a10851_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['tenant', 'closed_at'], name='invoices_in_tenant__0e7625_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents', django.db.models.expressions.CombinedExpression(models.F('subtotal_cents'), '+', models.F('tax_cents')))), name='invoices_total_equals_subtotal_plus_tax'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('closed_at__isnull', False), _connector='OR'), name='invoices_paid_requires_closed_at'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'void'), ('voided_at__isnull', False)), models.Q(models.Q(('status', 'void'), _negated=True), ('voided_at__isnull', True)), _connector='OR'), name='invoices_void_requires_voided_at'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='invoice_lines_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_subtotal_cents', django.db.models.expressions.CombinedExpression(models.F('quantity'), '*', models.F('unit_price_cents')))), name='invoice_lines_subtotal_matches_qty_times_price'),
        ),
    ]
