# Generated by Django 5.1.15 on 2026-05-05 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_add_invoice_number'),
        ('products', '0001_initial'),
        ('services', '0003_add_code_tax_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelineitem',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Source retail product. Null for service / ad-hoc lines. Mutually exclusive with `service` (a line is either a service or a product, never both).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='products.product'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Source service. Null for retail / ad-hoc lines.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='services.service'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(('service__isnull', True), ('product__isnull', True), _connector='OR'), name='invoice_lines_service_xor_product'),
        ),
    ]
