# Generated by Django 5.1.15 on 2026-05-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoicelineitem_invoice_lines_service_xor_product_and_more'),
        ('memberships', '0001_initial'),
        ('packages', '0001_initial'),
        ('products', '0001_initial'),
        ('services', '0003_add_code_tax_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoicelineitem',
            name='invoice_lines_at_most_one_source',
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='membership_plan',
            field=models.ForeignKey(blank=True, help_text='Source membership plan. Null for service / product / package / ad-hoc lines. When set, a `Subscription` row is created tied 1:1 to this line and flipped ACTIVE when the invoice closes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='memberships.membershipplan'),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='package',
            field=models.ForeignKey(blank=True, help_text='Source catalog package. Null for service / product / membership / ad-hoc lines. When set, a `PurchasedPackage` row is created tied 1:1 to this line and flipped ACTIVE when the invoice closes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='packages.package'),
        ),
        migrations.AddConstraint(
            model_name='invoicelineitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('service__isnull', True), ('product__isnull', True), _connector='OR'), models.Q(('service__isnull', True), ('package__isnull', True), _connector='OR'), models.Q(('service__isnull', True), ('membership_plan__isnull', True), _connector='OR'), models.Q(('product__isnull', True), ('package__isnull', True), _connector='OR'), models.Q(('product__isnull', True), ('membership_plan__isnull', True), _connector='OR'), models.Q(('package__isnull', True), ('membership_plan__isnull', True), _connector='OR')), name='invoice_lines_at_most_one_source'),
        ),
    ]
