# Generated by Django 5.1.15 on 2026-05-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_remove_invoicelineitem_invoice_lines_at_most_one_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gift_card_credits_cents',
            field=models.PositiveIntegerField(default=0, help_text='Total of gift card balances applied toward this invoice. Reduces amount_due_cents (which is what payment_method covers at close).'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('card_external', 'Card (external terminal)'), ('gift_card', 'Gift card (full coverage)'), ('other', 'Other')], max_length=20),
        ),
    ]
