# Generated by Django 5.1.15 on 2026-05-27 15:42

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_appointmentservice_provider'),
        ('customers', '0005_customer_referred_by'),
        ('invoices', '0007_invoice_gift_card_credits_cents_and_more'),
        ('tenants', '0012_tenant_confirmation_sms_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invoice',
            name='invoices_total_equals_subtotal_plus_tax',
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_discount_cents',
            field=models.PositiveIntegerField(default=0, help_text='Derived cents knocked off the invoice. Computed by `recalculate_totals` from kind + input + line basis, capped at the after-line-discount basis (never below $0).'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_discount_input',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Operator-typed value. For 'amount' kind: dollars off (5.00 = $5). For 'percent' kind: percent off (10.00 = 10%).", max_digits=8),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_discount_kind',
            field=models.CharField(choices=[('amount', 'Amount off ($)'), ('percent', 'Percent off (%)')], default='amount', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_discount_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoice',
            name='line_discounts_total_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount_cents',
            field=models.PositiveIntegerField(default=0, help_text='Derived cents off this line. Computed in `save()` from kind + input, capped at `line_subtotal_cents`.'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount_input',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Operator-typed value. For 'amount' kind: dollars off this line. For 'percent' kind: percent off this line.", max_digits=8),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount_kind',
            field=models.CharField(choices=[('amount', 'Amount off ($)'), ('percent', 'Percent off (%)')], default='amount', max_length=10),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='discount_reason',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='invoice_discount_share_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.CheckConstraint(condition=models.Q(('total_cents', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal_cents'), '-', models.F('line_discounts_total_cents')), '-', models.F('invoice_discount_cents')), '+', models.F('tax_cents')))), name='invoices_total_equals_subtotal_minus_discounts_plus_tax'),
        ),
    ]
