# Generated by Django 5.1.15 on 2026-05-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_remove_invoice_invoices_total_equals_subtotal_plus_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('check', 'Check'), ('card_external', 'Card (external terminal)'), ('card_stripe', 'Card (Lumè / Stripe)'), ('gift_card', 'Gift card (full coverage)'), ('other', 'Other')], max_length=20),
        ),
    ]
