# Generated by Django 5.1.15 on 2026-05-05 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_email_marketing_consent_at_and_more'),
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('filter_spec', models.JSONField(blank=True, default=dict)),
                ('last_member_count', models.PositiveIntegerField(default=0)),
                ('last_counted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiences_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_count_snapshot', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('suppressed_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='marketing.audience')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('recipient_email_domain', models.CharField(blank=True, default='', max_length=120)),
                ('recipient_phone_last4', models.CharField(blank=True, default='', max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('suppressed', 'Suppressed')], db_index=True, default='pending', max_length=20)),
                ('suppression_reason', models.CharField(blank=True, default='', help_text="e.g. 'no_consent', 'suppressed_unsubscribe', 'suppressed_bounce', 'suppressed_complaint', 'quiet_hours' (sms only)", max_length=50)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='send_log', to='marketing.campaign')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marketing_sends', to='customers.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketing_templates_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='marketing.marketingtemplate'),
        ),
        migrations.AddIndex(
            model_name='audience',
            index=models.Index(fields=['tenant', 'name'], name='marketing_a_tenant__51254b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='audience',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='marketingsendlog',
            index=models.Index(fields=['tenant', 'customer', '-created_at'], name='marketing_m_tenant__8fc46b_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingsendlog',
            index=models.Index(fields=['tenant', 'campaign', 'status'], name='marketing_m_tenant__fe6d4f_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingsendlog',
            index=models.Index(fields=['tenant', 'provider_message_id'], name='marketing_m_tenant__b62b9d_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingtemplate',
            index=models.Index(fields=['tenant', 'channel', 'is_active'], name='marketing_m_tenant__56a0c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketingtemplate',
            unique_together={('tenant', 'name')},
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'status', '-created_at'], name='marketing_c_tenant__86a82d_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'audience'], name='marketing_c_tenant__771986_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['tenant', 'scheduled_at'], name='marketing_c_tenant__3f44a3_idx'),
        ),
    ]
