# Generated by Django 5.1.15 on 2026-05-05 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('trigger_type', models.CharField(choices=[('birthday', 'Birthday month'), ('no_visit_days', 'No visit in N days (win-back)'), ('first_visit_anniversary', 'First-visit anniversary')], max_length=40)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('dedup_window_days', models.PositiveIntegerField(default=365)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Operator toggle. New automations land disabled — turn on after testing the trigger eval + previewing the template + verifying suppression-eligible counts.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_eligible_count', models.PositiveIntegerField(default=0)),
                ('last_run_sent_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='automations', to='marketing.audience')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='automations_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automations', to='marketing.marketingtemplate')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'trigger_type'], name='marketing_a_tenant__d9b220_idx')],
                'unique_together': {('tenant', 'name')},
            },
        ),
    ]
