# Generated by Django 5.1.15 on 2026-05-17 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_unsubscribetoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Lowercased recipient address. The lookup key.', max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('bounce_permanent', 'Permanent bounce'), ('complaint', 'Complaint'), ('manual', 'Manual')], db_index=True, max_length=32)),
                ('bounce_subtype', models.CharField(blank=True, default='', max_length=64)),
                ('complaint_subtype', models.CharField(blank=True, default='', max_length=64)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('event_count', models.PositiveIntegerField(default=1)),
                ('ses_message_id', models.CharField(blank=True, default='', max_length=200)),
                ('raw_event', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True, default='', help_text='Operator notes (manual additions); SES event summary otherwise.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_suppressions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['reason', '-last_seen_at'], name='marketing_e_reason_78fd36_idx')],
            },
        ),
    ]
