# Generated by Django 5.1.15 on 2026-05-29 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0015_alter_tenant_trial_ends_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe_connect', 'Stripe Connect'), ('custom', 'Custom merchant')], default='stripe_connect', help_text='Which payment processor this tenant uses. Stripe Connect is the self-serve default; Custom is the Pro+ bring-your-own option.', max_length=32)),
                ('stripe_account_id', models.CharField(blank=True, default='', help_text="Stripe Connected Account ID (e.g. acct_1Abc…). Empty for tenants that haven't completed Express onboarding.", max_length=64)),
                ('charges_enabled', models.BooleanField(default=False, help_text='True when Stripe has approved this account to accept charges. Mirrored from `account.charges_enabled` via the account.updated webhook.')),
                ('payouts_enabled', models.BooleanField(default=False, help_text='True when Stripe has approved this account to receive payouts to its bank.')),
                ('details_submitted', models.BooleanField(default=False, help_text='True once the spa completes the Stripe-hosted onboarding form. Until this flips, the connect status UI shows a "complete onboarding" prompt.')),
                ('connected_at', models.DateTimeField(blank=True, help_text='When the Stripe Express account was first created for this tenant. Used for compliance reporting + ops dashboards.', null=True)),
                ('disabled_at', models.DateTimeField(blank=True, help_text='When the spa explicitly deauthorized the connection (or Stripe disabled it for compliance reasons). Set by the account.application.deauthorized webhook.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant_account', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Merchant account',
                'verbose_name_plural': 'Merchant accounts',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='payments_one_merchant_account_per_tenant')],
            },
        ),
    ]
