# Generated by Django 5.1.15 on 2026-05-29 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_remove_invoice_invoices_total_equals_subtotal_plus_tax_and_more'),
        ('payments', '0001_initial'),
        ('tenants', '0015_alter_tenant_trial_ends_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(help_text="Gross charge amount in cents. What the customer's card is hit for.")),
                ('fee_cents', models.PositiveIntegerField(default=0, help_text='Stripe processing fee in cents (2.9%% + 30¢ for standard cards). Filled in when the balance_transaction expands on webhook.')),
                ('net_cents', models.PositiveIntegerField(default=0, help_text="What lands in the spa's Stripe balance — amount_cents − fee_cents.")),
                ('currency', models.CharField(default='usd', help_text='ISO-4217 currency code, lowercase per Stripe convention.', max_length=3)),
                ('stripe_payment_intent_id', models.CharField(help_text='Stripe PaymentIntent ID (pi_…). Idempotency key for the webhook handler — a duplicate event with the same PI matches the existing row.', max_length=64, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, default='', help_text='Stripe Charge ID (ch_…). Empty until the payment_intent.succeeded webhook lands.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', help_text='Lifecycle: pending → succeeded | failed. Set succeeded/failed by webhook handler; never UPDATEd after that.', max_length=16)),
                ('failure_code', models.CharField(blank=True, default='', help_text='Stripe failure_code on declined / errored payments (e.g. card_declined, expired_card). Helps the operator coach the customer on retry.', max_length=64)),
                ('failure_message', models.CharField(blank=True, default='', help_text='Human-readable failure message from Stripe. Surfaced in the invoice activity log on failed charges.', max_length=255)),
                ('last4', models.CharField(blank=True, default='', help_text='Last 4 digits of the card used. PCI SAQ-A compliant; appears on the customer receipt.', max_length=4)),
                ('brand', models.CharField(blank=True, default='', help_text='Card brand (visa / mastercard / amex / discover / etc.). Mostly for receipt display.', max_length=24)),
                ('refunded_cents', models.PositiveIntegerField(default=0, help_text="Sum of every Refund row's amount_cents for this Charge. Denormalized so list views can filter for fully/partially refunded without joining the ledger.")),
                ('initiated_via', models.CharField(choices=[('operator', 'Operator (invoice page)'), ('customer_portal', 'Customer portal (self-pay)')], default='operator', help_text='Where the charge originated — useful for analytics and the activity log.', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Operator who hit "Charge card" on the invoice. Null when the customer self-paid through the portal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charges_initiated', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(help_text='The invoice this charge pays toward. PROTECT because deleting an invoice with charges on it would silently break the audit trail.', on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='invoices.invoice')),
                ('merchant_account', models.ForeignKey(help_text='Which spa-side merchant account took the money. Almost always tenant.merchant_account but stored explicitly so the link survives if the spa later switches providers.', on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='payments.merchantaccount')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Charge',
                'verbose_name_plural': 'Charges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField(help_text='Refund amount in cents. Must be > 0 and <= charge.refundable_cents at the time the row is created.')),
                ('reason', models.CharField(help_text='Operator-typed reason. Stripe accepts duplicate / fraudulent / requested_by_customer as standard codes, but we accept free text for the audit trail.', max_length=255)),
                ('stripe_refund_id', models.CharField(help_text='Stripe Refund ID (re_…). Idempotency key for the webhook handler.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', help_text='Lifecycle: pending → succeeded | failed. Card refunds usually settle in seconds but ACH refunds can take days.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.ForeignKey(help_text='The original charge this refund undoes (fully or partially).', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.charge')),
                ('created_by', models.ForeignKey(blank=True, help_text='Operator who issued the refund. Null for refunds issued from Stripe Express dashboard directly (webhook still creates the row for the local ledger).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_issued', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['tenant', '-created_at'], name='payments_ch_tenant__d13694_idx'),
        ),
        migrations.AddIndex(
            model_name='charge',
            index=models.Index(fields=['invoice', '-created_at'], name='payments_ch_invoice_df128a_idx'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_cents__lte', models.F('amount_cents'))), name='payments_charge_refunded_lte_amount'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='payments_charge_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['tenant', '-created_at'], name='payments_re_tenant__462b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['charge', '-created_at'], name='payments_re_charge__b86c8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cents__gt', 0)), name='payments_refund_amount_positive'),
        ),
    ]
