# Generated by Django 5.1.15 on 2026-05-05 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0009_tenant_online_booking_cancellation_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#6b7280', help_text='Hex color for the product chip on the catalog list.', max_length=7)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'product categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, db_index=True, help_text='Stock-keeping unit. Auto-generated from the name on first save; editable. Unique within the tenant.', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('price_cents', models.PositiveIntegerField(default=0, help_text='Sale price in cents. Snapshotted onto invoice lines.')),
                ('cost_cents', models.PositiveIntegerField(default=0, help_text='Wholesale cost in cents (for margin reports). Optional. Never displayed on customer-facing surfaces.')),
                ('tax_rate_percent', models.DecimalField(decimal_places=3, default=0, help_text='Tax rate as a percent (e.g. 8.875 for NYC combined). Snapshotted onto the invoice line at sale time.', max_digits=6)),
                ('track_inventory', models.BooleanField(default=True, help_text='When false, sales do not decrement stock. Use for gift cards / digital items / consultation fees.')),
                ('stock_quantity', models.IntegerField(default=0, help_text='Current count on hand. Signed integer so backorders show as negative rather than clamping to zero.')),
                ('low_stock_threshold', models.PositiveIntegerField(default=0, help_text='When stock_quantity drops to or below this number, the product is flagged "low stock" on the catalog list. 0 disables the warning.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive products stay in history (existing invoice lines) but cannot be sold on new invoices.')),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['tenant', 'is_active', 'name'], name='products_pr_tenant__df0219_idx'), models.Index(fields=['tenant', 'category'], name='products_pr_tenant__a8981a_idx'), models.Index(fields=['tenant', 'sku'], name='products_pr_tenant__832bf8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('tenant', 'sku'), name='products_unique_tenant_sku')],
            },
        ),
    ]
