# Generated by Django 5.1.15 on 2026-05-16 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0012_tenant_confirmation_sms_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('zenoti', 'Zenoti'), ('vagaro', 'Vagaro'), ('mindbody', 'Mindbody'), ('boulevard', 'Boulevard')], db_index=True, max_length=20)),
                ('mode', models.CharField(choices=[('dry_run', 'Dry-run (no writes)'), ('commit', 'Commit (writes)')], max_length=10)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('started_by', models.ForeignKey(blank=True, help_text='Staff member or platform admin who kicked off the run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ('-started_at',),
                'indexes': [models.Index(fields=['tenant', 'vendor', '-started_at'], name='imports_imp_tenant__62b3ac_idx')],
            },
        ),
    ]
